import {describe,it,expect} from 'vitest';
import {developmentUrls,discoverHomes,galleryImages} from '../src/adapters/cala/site-parser.js';
import {matchedPage} from '../src/reports/matched-page.js';
describe('Cala public sources',()=>{
 it('deduplicates developments from plot and availability URLs',()=>expect(developmentUrls('<urlset><url><loc>https://www.cala.co.uk/homes-for-sale/scotland/edinburgh/site/12/</loc></url><url><loc>https://www.cala.co.uk/homes-for-sale/scotland/edinburgh/site/availability-prices/</loc></url><url><loc>https://www.cala.co.uk/homes-for-sale/scotland/edinburgh/</loc></url></urlset>')).toEqual(['https://www.cala.co.uk/homes-for-sale/scotland/edinburgh/site/availability-prices/']));
 it('uses plot attributes and excludes enquiry links',()=>{const data=discoverHomes('<h1>Development</h1><div id="plot-list"><div data-bedrooms="5" data-price="800000" data-housetype="Detached" data-reserved="false"><h3>Plot 12 - Yew</h3><a href="?ufprt=private">Enquire</a><a href="/homes-for-sale/scotland/edinburgh/site/12/">Details</a></div></div>','https://www.cala.co.uk/homes-for-sale/scotland/edinburgh/site/availability-prices/');expect(data.plots[0]).toMatchObject({name:'Yew',plotNumber:'12',bedrooms:5,price:800000,available:true,isDetached:true});});
 it('inspects reserved plots without a details link',()=>{const data=discoverHomes('<h1>Development</h1><div id="plot-list"><div data-bedrooms="5" data-reserved="true"><h3>Plot 76 - Willow</h3></div></div>','https://www.cala.co.uk/homes-for-sale/south-east-england/kent/site/availability-prices/');expect(data.plots[0]).toMatchObject({url:'https://www.cala.co.uk/homes-for-sale/south-east-england/kent/site/76/',available:false,bedrooms:5});});
 it('extracts full gallery originals without unrelated media',()=>expect(galleryImages('<div class="plot-gallery"><img src="/media/a/photo.jpg?width=750"><img src="/media/a/photo.jpg?width=375"></div><img src="/media/icon.jpg">').map(i=>i.url)).toEqual(['https://www.cala.co.uk/media/a/photo.jpg']));
 it('brands the independent collection for Cala',()=>{const page=matchedPage({builder:{name:'Cala',slug:'cala',websiteUrl:'https://www.cala.co.uk'},status:'completed',startedAt:'now',model:'test',question:'test',developments:[],properties:[],images:[],errors:[],metrics:{}});expect(page).toContain('Cala');expect(page).not.toContain('Bellway');expect(page).toContain('href="../index.html"');});
});
