import {expect,it} from 'vitest';
import {developmentUrls,discoverHomes,galleryImages,enrichPage} from '../src/adapters/castle-green/site-parser';
import {isInferredAnalysis} from '../src/vision/analysis-provenance';
const origin='https://www.castlegreenhomes.uk',url=origin+'/our-developments/north-wales/park/';
it('discovers developments and advertised two-bedroom homes without plot caps',()=>{expect(developmentUrls(`<urlset><url><loc>${url}</loc></url><url><loc>${url}the-home/</loc></url></urlset>`)).toEqual([url]);const result=discoverHomes(`<h1>Park</h1><div class="house-type-card"><p class="house-name"><a href="${url}the-home/">The Home</a></p>Bedrooms: 2 from £250,000</div>`,url);expect(result.plots[0]).toMatchObject({name:'The Home',bedrooms:2,price:250000});expect(result.homes[1].propertyType).toBe('development');});
it('uses full photos, retains SVG floorplans and rejects other origins',()=>{const images=galleryImages(`<img src="/logo.svg"><img data-img="${origin}/app/uploads/room.jpg" src="/thumbnail.jpg"><div class="image-wrapper-inner"><img src="/app/uploads/plan.svg"></div>`);expect(images.map(i=>i.url)).toEqual([origin+'/app/uploads/room.jpg',origin+'/app/uploads/plan.svg']);expect(()=>galleryImages('<img data-img="https://other.com/room.jpg">')).toThrow();});
it('preserves map coordinates before scripts are sanitised',async()=>{expect(await enrichPage('<body><script>parentLat = parseFloat(53.3); parentLong = parseFloat(-2.6)</script></body>')).toContain('"latitude":53.3');});
it('rejects filename-derived verdicts while allowing real image descriptions',()=>{expect(isInferredAnalysis({description:'Interior space interior showing contemporary design, styling and finishes.'})).toBe(true);expect(isInferredAnalysis({description:'A kitchen with white cabinets and a wooden dining table.'})).toBe(false);});
it('chooses an official responsive image within the processing size limit',()=>{const images=galleryImages(`<div class="fadeSlide"><img src="/app/uploads/huge.png" srcset="/app/uploads/huge.png 8000w, /app/uploads/medium.png 2048w, /app/uploads/small.png 1024w"></div>`);expect(images[0].url).toBe(origin+'/app/uploads/medium.png');});
