import {it,expect,vi,beforeEach} from 'vitest';
import {resolve} from 'node:path';
const fake=vi.hoisted(()=>({files:new Map<string,string>(),calls:[] as string[][],failPush:false,staged:false,imports:vi.fn(),publish:vi.fn()}));
vi.mock('node:child_process',()=>({execFile:Object.assign(()=>{},{[Symbol.for('nodejs.util.promisify.custom')]:async(_command:string,args:string[])=>{
 fake.calls.push(args);
 if(args[0]==='push'&&fake.failPush)throw new Error('Push unavailable');
 if(args[0]==='add')fake.staged=true;
 if(args[0]==='commit')fake.staged=false;
 const stdout=args[0]==='branch'?'main':args[0]==='rev-parse'?(args.includes('HEAD')?'commit123':'origin/main'):args[0]==='diff'&&args.includes('--name-only')&&fake.staged?'classification-reports/alpha.json':'';
 return {stdout};
}})}));
vi.mock('node:fs/promises',()=>({mkdir:async()=>{},writeFile:async(p:string,s:string)=>{fake.files.set(p,s);},rename:async(a:string,b:string)=>{fake.files.set(b,fake.files.get(a)!);fake.files.delete(a);},copyFile:async()=>{},readFile:async(p:string)=>{if(!fake.files.has(p))throw Object.assign(new Error('missing'),{code:'ENOENT'});return fake.files.get(p);}}));
vi.mock('../src/reports/report',()=>({writeReport:async()=>{}}));
vi.mock('../src/database/postgres',()=>({createDatabase:()=>({end:async()=>{}})}));
vi.mock('../src/catalogue/import',()=>({importBuilder:fake.imports}));
vi.mock('../src/catalogue/publish',()=>({publishWebsite:fake.publish}));
import {preparePublication,developmentPublication} from '../src/cli/classification-publication';
import type {RunReport} from '../src/reports/report';
beforeEach(()=>{fake.files.clear();fake.calls=[];fake.failPush=false;fake.staged=false;vi.clearAllMocks();});
it('retains a failed push and retries it before the next development without repeating database publication',async()=>{
 const folder=resolve('collections/alpha-home-offices');
 const report={images:[],properties:[]} as unknown as RunReport;
 fake.files.set(resolve(folder,'results.json'),JSON.stringify(report));
 expect(await preparePublication()).toBe('main');
 fake.failPush=true;
 await expect(developmentPublication('alpha',folder,'First',report,'main')).rejects.toThrow('Push unavailable');
 expect(fake.imports).toHaveBeenCalledTimes(1);expect(fake.publish).toHaveBeenCalledTimes(1);
 const checkpoint=resolve('.showhome/classification-publication.json');
 expect(JSON.parse(fake.files.get(checkpoint)!).phase).toBe('push');
 const stage=fake.calls.find(args=>args[0]==='add')!;
 expect(stage).toContain('classification-reports/alpha.json');
 expect(stage.some(p=>p.endsWith('full-report.html'))).toBe(true);
 expect(stage.some(p=>p.includes('images/'))).toBe(false);
 fake.failPush=false;
 await preparePublication();
 expect(fake.imports).toHaveBeenCalledTimes(1);expect(fake.publish).toHaveBeenCalledTimes(1);
 expect(JSON.parse(fake.files.get(checkpoint)!).phase).toBe('done');
 expect(fake.calls.filter(args=>args[0]==='push')).toHaveLength(2);
});
