import {describe,it,expect,vi} from 'vitest';
import {JSDOM} from 'jsdom';
import {matchedPage} from '../src/reports/matched-page.js';
import type {RunReport} from '../src/reports/report.js';
const report:RunReport={status:'completed',startedAt:'now',model:'test',question:'test',developments:[],errors:[],metrics:{},properties:[{development:'Test site',developmentUrl:'https://example.com/site',name:'House',url:'https://example.com/home',bedrooms:5,price:null,plots:[],imageIds:['one','two','three']}],images:['one','two','three'].map(id=>({id,path:`images/${id}.jpg`,sourceUrl:'https://example.com/'+id,verdict:{matches:true,hasDesk:true,hasBed:false,roomType:'office',description:id==='one'?'Office </script><script>bad()</script>':id,reason:'Desk and no bed'}}))};
function page(favouritesOnly=false,hash=''){
 return new JSDOM(matchedPage(report,favouritesOnly),{url:'https://local.test/results/index.html'+hash,runScripts:'dangerously',pretendToBeVisual:true,beforeParse(window){window.matchMedia=(()=>({matches:true})) as never;window.HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','');};window.HTMLDialogElement.prototype.close=function(){this.removeAttribute('open');this.dispatchEvent(new window.Event('close'));};}});
}
describe('Interactive image collections',()=>{
 it('shows each home type once and keeps development and plot details inside the expanded panel',()=>{const shared:RunReport={...report,images:[report.images[0]!],properties:[51,2,1].map(n=>({...report.properties[0]!,name:'Lamberton · Plot '+n,development:'Lamberton site',url:'https://example.com/plot-'+n,plots:[{number:String(n),price:500000,available:true}],imageIds:['one']}))};const dom=new JSDOM(matchedPage(shared));try{const card=dom.window.document.querySelector('.office-card')!;expect(card.querySelector('h3')!.textContent).toBe('Lamberton');const details=card.querySelector('details')!;expect(details.querySelector('summary')!.textContent).toContain('Explore this home');for(const n of [51,2,1])expect(details.textContent).toContain('Plot '+n);expect(details.textContent).toContain('Lamberton site');const body=card.querySelector('.card-body')!.cloneNode(true) as HTMLElement;body.querySelector('details')!.remove();expect(body.textContent).not.toContain('Plot');expect(body.textContent).not.toContain('Lamberton site');}finally{dom.window.close();}});

 it('wraps the carousel and navigates fullscreen with keyboard arrows',()=>{const dom=page();try{const {document,KeyboardEvent}=dom.window;const hero=document.getElementById('hero-image') as HTMLImageElement;document.querySelector<HTMLButtonElement>('[data-step="-1"]')!.click();expect(hero.getAttribute('src')).toBe('images/three.jpg');document.querySelector<HTMLButtonElement>('[data-open=""]')!.click();expect(document.getElementById('viewer')!.hasAttribute('open')).toBe(true);document.body.dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true}));expect(document.getElementById('viewer-image')!.getAttribute('src')).toBe('images/one.jpg');document.getElementById('viewer-close')!.click();expect(document.getElementById('viewer')!.hasAttribute('open')).toBe(false);expect(document.body.style.overflow).toBe('');}finally{dom.window.close();}});
 it('swipes in both directions with wrapping, preserves scrolling and taps, and cancels multi-touch gestures',()=>{const dom=page();try{const {document,Event}=dom.window;const surface=document.querySelector('.hero-image-button')!,hero=document.getElementById('hero-image')!;const touch=(type:string,x:number,y:number,count=1)=>{const event=new Event(type,{bubbles:true,cancelable:true});const point={identifier:1,clientX:x,clientY:y};Object.defineProperties(event,{touches:{value:type==='touchstart'?Array.from({length:count},()=>point):[]},changedTouches:{value:[point]}});surface.dispatchEvent(event);};touch('touchstart',150,50);touch('touchend',60,55);expect(hero.getAttribute('src')).toBe('images/two.jpg');(surface as HTMLButtonElement).click();expect(document.getElementById('viewer')!.hasAttribute('open')).toBe(false);touch('touchstart',50,50);touch('touchend',150,50);expect(hero.getAttribute('src')).toBe('images/one.jpg');touch('touchstart',50,50);touch('touchend',150,50);expect(hero.getAttribute('src')).toBe('images/three.jpg');for(const gesture of ['vertical','cancel','multi']){touch('touchstart',150,50,gesture==='multi'?2:1);if(gesture==='cancel')touch('touchcancel',100,50);touch('touchend',60,gesture==='vertical'?200:50);expect(hero.getAttribute('src')).toBe('images/three.jpg');}document.querySelector<HTMLButtonElement>('[data-image-id="one"] [data-open]')!.click();const stage=document.querySelector('.viewer-stage')!;for(const [type,x] of [['touchstart',150],['touchend',50]] as const){const event=new Event(type,{bubbles:true});const point={identifier:2,clientX:x,clientY:50};Object.defineProperties(event,{touches:{value:type==='touchstart'?[point]:[]},changedTouches:{value:[point]}});stage.dispatchEvent(event);}expect(document.getElementById('viewer-image')!.getAttribute('src')).toBe('images/two.jpg');}finally{dom.window.close();}});
 it('keeps the inline image clear and reveals fullscreen controls only during activity',()=>{const dom=page();try{const {document,Event}=dom.window;expect(document.querySelector('#hero-carousel [data-thumbnails]')).toBeNull();expect(document.getElementById('hero-position')).toBeNull();expect(document.getElementById('viewer-position')).toBeNull();let idle: (()=>void)|undefined;vi.spyOn(dom.window,'setTimeout').mockImplementation(((callback:()=>void,delay:number)=>{if(delay===1800)idle=callback;return 123;}) as never);document.querySelector<HTMLButtonElement>('[data-open=""]')!.click();const viewer=document.getElementById('viewer')!;expect(viewer.classList.contains('controls-visible')).toBe(true);idle!();expect(viewer.classList.contains('controls-visible')).toBe(false);viewer.dispatchEvent(new Event('pointermove',{bubbles:true}));expect(viewer.classList.contains('controls-visible')).toBe(true);expect(document.querySelectorAll('#viewer-save svg, #viewer-close svg')).toHaveLength(2);expect(document.getElementById('viewer-save')!.getAttribute('aria-label')).toBe('Add to favourites');}finally{dom.window.close();}});
 it('keeps thumbnails in place while changing images and applies a gentle hover lens',()=>{const dom=page();try{const {document,MouseEvent,Event}=dom.window;dom.window.matchMedia=(()=>({matches:false})) as never;document.querySelector<HTMLButtonElement>('[data-open=""]')!.click();const strip=document.querySelector<HTMLElement>('[data-thumbnails]')!;const first=strip.querySelector<HTMLButtonElement>('button')!;document.querySelector<HTMLButtonElement>('.viewer-next')!.click();expect(strip.querySelector('button')).toBe(first);Object.defineProperty(first,'getBoundingClientRect',{value:()=>({left:0,width:100})});strip.dispatchEvent(new MouseEvent('pointermove',{clientX:50,bubbles:true}));expect(first.style.transform).toContain('scale(1.35)');strip.dispatchEvent(new Event('pointerleave'));expect(first.style.transform).toBe('');for(const button of document.querySelectorAll('.viewer-header button,.viewer-arrow'))expect(button.querySelector('svg')?.getAttribute('viewBox')).toBe('0 0 24 24');}finally{dom.window.close();}});
 it('stores favourites and carries them through local-page navigation links',()=>{const dom=page();try{const {document,localStorage}=dom.window;document.querySelector<HTMLButtonElement>('.card-save')!.click();expect(JSON.parse(localStorage.getItem('showhome-favourites-v1')!)).toEqual(['one']);const link=document.querySelector<HTMLAnchorElement>('[data-favourites-link="../favourites.html"]')!;expect(JSON.parse(decodeURIComponent(new URL(link.href).hash.slice(12)))).toEqual(['one']);document.querySelector<HTMLButtonElement>('.card-save')!.click();expect(JSON.parse(localStorage.getItem('showhome-favourites-v1')!)).toEqual([]);}finally{dom.window.close();}});
 it('shows only favourites and removes the last favourite from the carousel',()=>{const dom=page(true,'#favourites='+encodeURIComponent(JSON.stringify(['two'])));try{const {document}=dom.window;expect([...document.querySelectorAll<HTMLElement>('.office-card')].filter(c=>!c.hidden).map(c=>c.dataset.imageId)).toEqual(['two']);expect(document.getElementById('hero-image')!.getAttribute('src')).toBe('images/two.jpg');document.querySelector<HTMLButtonElement>('[data-image-id="two"] .card-save')!.click();expect((document.getElementById('hero-carousel') as HTMLElement).hidden).toBe(true);expect((document.getElementById('empty') as HTMLElement).hidden).toBe(false);expect(document.getElementById('empty')!.textContent).toContain('No favourites yet');expect(JSON.parse(decodeURIComponent(dom.window.location.hash.slice(12)))).toEqual([]);}finally{dom.window.close();}});
 it('handles an empty collection without executing injected descriptions',()=>{const dom=new JSDOM(matchedPage({...report,images:[],properties:[]}),{url:'https://local.test',runScripts:'dangerously',pretendToBeVisual:true});try{expect(dom.window.document.getElementById('result-count')!.textContent).toBe('0 office images');}finally{dom.window.close();}});
});
