import {describe,it,expect} from 'vitest';
import {GeminiModelPool,classificationModels,SMALL_GEMINI_MODELS} from '../src/vision/gemini-model-pool.js';
const failure=(status:number)=>Object.assign(new Error(`Gemini HTTP ${status}`),{status});
describe('Small Gemini model quota pool',()=>{
 it('immediately switches on quota and returns the successful model for provenance',async()=>{const pool=new GeminiModelPool(['small-a','small-b']);const calls:string[]=[];const request=async(model:string)=>{calls.push(model);if(model==='small-a')throw failure(429);return 'analysis';};expect(await pool.run(request)).toEqual({model:'small-b',value:'analysis'});await pool.run(request);expect(calls).toEqual(['small-a','small-b','small-b']);expect(pool.snapshot().modelStates[0]?.status).toBe('quota_wait');});
 it('waits only after the whole pool is exhausted and retries cooled models after two minutes',async()=>{let now=0;const pool=new GeminiModelPool(['a','b','c'],()=>now);const calls:string[]=[];const request=async(model:string)=>{calls.push(model);throw failure(429);};await expect(pool.run(request)).rejects.toMatchObject({status:429,retrySeconds:120});expect(calls).toEqual(['a','b','c']);await expect(pool.run(request)).rejects.toMatchObject({status:429});expect(calls).toHaveLength(3);now=120000;expect(await pool.run(async()=>true)).toEqual({model:'a',value:true});});
 it('skips unavailable models while preserving authentication and server failures',async()=>{const pool=new GeminiModelPool(['a','b']);const result=await pool.run(async model=>{if(model==='a')throw failure(404);return true;});expect(result.model).toBe('b');expect(pool.snapshot().modelStates[0]?.status).toBe('unavailable');for(const status of [401,403,503]){const calls:string[]=[];await expect(pool.run(async model=>{calls.push(model);throw failure(status);})).rejects.toMatchObject({status});expect(calls).toEqual(['b']);}});
 it('uses only stable Flash-Lite models, without alias duplicates or costly Pro models',()=>{expect(classificationModels('gemini-2.5-flash-lite')[0]).toBe('gemini-2.5-flash-lite');expect(classificationModels('gemini-pro')).toEqual([...SMALL_GEMINI_MODELS]);expect(new Set(classificationModels()).size).toBe(3);});
});
