import {load} from 'cheerio';
import type {PropertyCandidate,GalleryImageCandidate} from '../../models/domain.js';
const origin='https://www.berkeleygroup.co.uk';
// These sitemap entries are local-area editorial guides, not developments.
const areaGuides=new Set(['places-to-dine-and-drink-in-fleet','schools-in-fleet','healthy-living-in-fleet','travel-in-fleet','shopping-in-fleet']);
export function developmentUrls(xml:string){const $=load(xml,{xmlMode:true});return [...new Set($('url > loc').map((_,e)=>$(e).text().trim()).get().filter(u=>new URL(u).origin===origin&&!areaGuides.has(new URL(u).pathname.split('/').filter(Boolean).at(-1)!)&&/^\/developments\/[^/]+\/[^/]+\/[^/]+(?:\/[^/]+)?\/?$/.test(new URL(u).pathname)))];}
export async function enrichPage(html:string,fetchText:(url:string)=>Promise<string>){const $=load(html);const id=$('.data-source-page-id').first().attr('value');if(!id||!$('.property-list-component').length)return html;const u=new URL('/search_api/properties',origin);u.search=new URLSearchParams({noOfItemsPerPage:'10',dataSourcePageId:id,status:'',selectedPrice:'',selectedPropertyType:'',selectedNoOfBedrooms:''}).toString();const data=JSON.parse(await fetchText(u.href));if(data.status!=='success'||!Array.isArray(data.data?.items))throw new Error('Missing public property table');return html+'<script type="application/json" id="crawler-properties">'+JSON.stringify(data.data).replace(/</g,'\\u003c')+'</script>';}
export function discoverHomes(html:string,url:string){const $=load(html);const name=$('h1').first().text().trim();if(!name)throw new Error('Missing development heading');const raw=$('#crawler-properties').text();if(!raw){if(/all sold|development completed|coming soon|no properties available/i.test($('main').text()))return {development:{name,url},homes:[] as PropertyCandidate[],plots:[] as PropertyCandidate[],plotError:null};throw new Error('No supported property availability table');}const data=JSON.parse(raw);const plots:PropertyCandidate[]=data.items.map((p:any)=>{const f=p.fields,u=new URL(p.button.url,origin);if(u.origin!==origin)throw new Error('Unexpected property origin');return {externalId:'plot:'+u.href,name:f.phaseid?'Property '+f.propertynumber+' · '+f.phaseid:'Property '+f.propertynumber,url:u.href,plotNumber:f.propertynumber,bedrooms:Number(f.propertynoofbedrooms)||null,price:Number(f.propertyprice.replace(/[^\d.]/g,''))||null,propertyType:f.propertytype,isDetached:null,available:/\bavailable\b/i.test(f.propertystatus),status:f.propertystatus};});const homes=plots.filter(p=>/^\/development\/[^/]+\/property-/.test(new URL(p.url).pathname));const unlinked=plots.filter(p=>(p.bedrooms??0)>=5&&!homes.includes(p)).length;return {development:{name,url},homes,plots,plotError:unlinked?`${unlinked} qualifying property listings have no property details link; their galleries are unavailable.`:null};}
export function galleryImages(html:string):GalleryImageCandidate[]{const $=load(html);if(!/^Property\s+\S+/i.test($('h1').first().text().trim()))throw new Error('Unexpected property gallery page');const images=new Map<string,GalleryImageCandidate>();$('.image-carousel-component .main-slider-wrapper img').each((_,e)=>{const raw=$(e).attr('data-src')??$(e).attr('src');if(!raw)return;const u=new URL(raw,origin);if(u.origin!==origin||!u.pathname.startsWith('/-/media/'))throw new Error('Unexpected gallery origin');if(!images.has(u.pathname))images.set(u.pathname,{url:u.href,position:images.size,altText:$(e).attr('alt')});});return [...images.values()];}

export function houseTypeName(html:string):string|null {const $=load(html);if(!/^Property\s+\S+/i.test($('h1').first().text().trim()))return null;const names=$(".simple-callout-component h2").map((_,e)=>$(e).text().trim()).get().filter(n=>/^The [A-Z]/.test(n)&&n.length<80);return names.length===1?names[0]!:null;}
