import { readFile, writeFile, readdir } from 'node:fs/promises';
import {matchedPage} from './matched-page.js';
import {favouritesStateScript} from './gallery-ui.js';
import type { RunReport } from './report.js';
const e=(s:unknown)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export async function writeGateway(){
 const folders=(await readdir('results',{withFileTypes:true})).filter(e=>e.isDirectory()&&e.name.endsWith('-home-offices')).map(e=>e.name);
 const collections=await Promise.all(folders.map(async folder=>({folder,report:JSON.parse(await readFile(`results/${folder}/results.json`,'utf8')) as RunReport})));
 const combined: RunReport = {builder:{name:'Favourites',slug:'favourites',websiteUrl:''},status:'completed',startedAt:new Date().toISOString(),model:'Gemini',question:'Home office with no beds',developments:[],properties:[],images:[],errors:[],metrics:{}};
 for(const {folder,report} of collections){combined.images.push(...report.images.filter(i=>i.verdict?.matches).map(i=>({...i,path:folder+'/'+i.path})));combined.properties.push(...report.properties.map(p=>({...p,development:(report.builder?.name??'Bellway')+' · '+p.development})));}
 combined.images=[...new Map(combined.images.map(i=>[i.id,i])).values()];
 await writeFile('results/favourites.html',matchedPage(combined,true));
 const cards=collections.filter(({report})=>report.images.some(i=>i.verdict?.matches)).map(({folder,report})=>{const images=report.images.filter(i=>i.verdict?.matches);const homes=report.properties.filter(p=>p.imageIds.some(id=>images.some(i=>i.id===id)));const sites=new Set(homes.map(p=>p.developmentUrl));const name=report.builder?.name??'Bellway';return `<a class="card" href="${folder}/index.html" data-favourites-link="${folder}/index.html">${images[0]?`<img src="${folder}/${e(images[0].path)}" alt="${e(images[0].verdict?.description)}">`:'<div class="placeholder">Collection in progress</div>'}<div class="body"><p class="label">${e(report.status.replaceAll('_',' '))}</p><h2>${e(name)} <span>↗</span></h2><p>${images.length} office images · ${sites.size} developments · ${homes.length} matching properties</p><p class="small">${report.developments.length} sites checked · ${report.images.length} unique images collected · ${report.images.filter(i=>!i.verdict).length} pending</p></div></a>`;}).join('');
 await writeFile('results/index.html',`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Showhome collections</title><style>*{box-sizing:border-box}body{margin:0;background:#f5f2ed;color:#18283b;font:16px Arial,sans-serif}header,main,footer{max-width:1120px;margin:auto;padding:32px 24px}header{border-bottom:1px solid #d8d3c9;font-weight:bold;letter-spacing:2px}.label{font-size:11px;letter-spacing:2px;text-transform:uppercase;color:#776646}h1{font:clamp(40px,6vw,68px) Georgia,serif;margin:18px 0}h2{font:34px Georgia,serif;margin:12px 0}h2 span{float:right}.intro{max-width:650px;line-height:1.7;margin-bottom:35px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:28px}.card{display:block;background:white;text-decoration:none;color:inherit;border:1px solid #dfdbd2}.card:hover{border-color:#b99a5b}.card img,.placeholder{width:100%;height:300px;object-fit:cover}.placeholder{display:grid;place-items:center;background:#e7e2d8}.body{padding:25px}.body p{line-height:1.6}.small,footer{font-size:13px;color:#67717c}footer{line-height:1.7}@media(max-width:650px){.grid{grid-template-columns:1fr}.card img{height:240px}}</style></head><body><header>SHOWHOME CRAWLER <a style="float:right;font-size:13px;letter-spacing:0;color:inherit" href="favourites.html" data-favourites-link="favourites.html">Favourites ♡</a></header><main><p class="label">The collections · UK</p><h1>A space to work.<br>A home to explore.</h1><p class="intro">Browse home-office images from properties with five or more bedrooms. Each match shows a visible desk and no visible bed. Choose a developer to explore its saved images, property links and full crawl report.</p><div class="grid">${cards}</div></main><footer>Independent review of public example galleries. Galleries may be shared across plots and developments; matches are Gemini judgements. Updated ${e(new Date().toLocaleString('en-GB',{timeZone:'Europe/London'}))}.</footer><script>${favouritesStateScript}</script></body></html>`);
}
