import { writeFile, rename } from 'node:fs/promises';
import { randomUUID } from 'node:crypto';
import { matchedPage } from './matched-page.js';
import type { Verdict } from '../vision/gemini-classifier.js';
async function saveArtifact(path: string, body: string) {
 const temporary = path + '.' + randomUUID() + '.tmp';
 await writeFile(temporary, body);
 await rename(temporary, path);
}
export interface ReportImage { id: string; path: string; sourceUrl: string; verdict?: Verdict; analysisModel?: string; criteriaExclusion?: string; error?: string }
export interface ReportProperty { development: string; developmentUrl: string; name: string; url: string; bedrooms: number; price: number | null; plots: { number?: string; price: number | null; available: boolean }[]; imageIds: string[] }
export interface RunReport { builder?: {name:string;slug:string;websiteUrl:string}; status: string; startedAt: string; completedAt?: string; model: string; question: string; analysisVersion?: string; developments: { url: string; name?: string; status: string; homes?: number; qualifying?: number; error?: string; warning?: string }[]; properties: ReportProperty[]; images: ReportImage[]; errors: { url: string; stage: string; message: string }[]; metrics: Record<string, number>; }
const escape = (s: unknown) => String(s ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]!));
export async function writeReport(folder: string, report: RunReport) {
 await saveArtifact(`${folder}/results.json`, JSON.stringify(report, null, 2));
 await saveArtifact(`${folder}/checkpoint.json`, JSON.stringify(report, null, 2));
 const builder = escape(report.builder?.name ?? 'Bellway');
 const imageMap = new Map(report.images.map(image => [image.id, image]));
 const matched = report.properties.filter(p => p.imageIds.some(id => imageMap.get(id)?.verdict?.matches));
 const cards = matched.map(p => `<article><h2>${escape(p.development)} — ${escape(p.name)}</h2><p>${p.bedrooms} bedrooms · ${p.price === null ? 'Price unknown' : '£' + p.price.toLocaleString('en-GB')} · <a href="${escape(p.url)}">${builder} listing</a></p><p>Plots: ${escape(p.plots.map(plot => plot.number).join(', ') || 'House style advertised; no plot data')}</p>${p.imageIds.map(id => imageMap.get(id)).filter(image => image?.verdict?.matches).map(image => `<figure><a href="${escape(image!.path)}"><img loading="lazy" src="${escape(image!.path)}"></a><figcaption>${escape(image!.verdict!.description)}<br>${escape(image!.verdict!.reason)} · <a href="${escape(image!.sourceUrl)}">Source image</a></figcaption></figure>`).join('')}</article>`).join('');
 const pending = report.images.filter(i => !i.verdict).length;
 const allImages = `<details><summary>All unique images and decisions (${report.images.length})</summary><div class="image-grid">${report.images.map(image => `<figure><a href="${escape(image.path)}"><img loading="lazy" src="${escape(image.path)}"></a><figcaption><strong>${image.verdict ? image.verdict.matches ? 'MATCH' : 'NO MATCH' : 'PENDING / ERROR'}</strong><br>${escape(image.verdict?.description || image.error)}<br>${escape(image.verdict?.reason)}<br><a href="${escape(image.sourceUrl)}">Source</a></figcaption></figure>`).join('')}</div></details>`;
 const allProperties = `<details><summary>All qualifying house styles (${report.properties.length})</summary><table><tr><th>Development</th><th>House style</th><th>Bedrooms</th><th>Images</th><th>Matches</th></tr>${report.properties.map(p => `<tr><td>${escape(p.development)}</td><td><a href="${escape(p.url)}">${escape(p.name)}</a></td><td>${p.bedrooms}</td><td>${p.imageIds.length}</td><td>${p.imageIds.filter(id => imageMap.get(id)?.verdict?.matches).length}</td></tr>`).join('')}</table></details>`;
 await saveArtifact(`${folder}/full-report.html`, `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${builder} home offices — review</title><style>body{font:16px system-ui;max-width:1150px;margin:40px auto;padding:0 20px;background:#f6f5f2;color:#182538}article{background:white;padding:24px;margin:24px 0;border-radius:12px}img{width:100%;max-width:680px;border-radius:8px}figure{margin:20px 0}figcaption{max-width:680px;margin:8px 0}a{color:#145a8d}td,th{padding:8px;text-align:left;border-bottom:1px solid #ddd}summary{cursor:pointer;margin:20px 0;font-weight:600}.image-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:20px}.image-grid img{height:220px;object-fit:contain;background:#ddd}.image-grid figcaption{font-size:14px}</style><h1>${builder}: ${escape(report.question)}</h1><p>Status: <strong>${escape(report.status)}</strong> · Started ${escape(report.startedAt)} · Model ${escape([...new Set(report.images.filter(i=>i.verdict).map(i=>i.analysisModel ?? report.model))].join(', ') || report.model)}</p><p>Five or more bedrooms. No price or detached filter. Results are model judgements from example galleries, which may be reused and may not depict the exact plot.</p><p>${report.developments.length} developments recorded · ${report.properties.length} qualifying house styles · ${report.images.length} unique images · ${pending} pending/error images · ${matched.length} house styles with matches.</p><p><a href="results.json">All results (JSON)</a> · <a href="properties.csv">Properties (CSV)</a> · <a href="matches.csv">Matches (CSV)</a></p>${cards || '<p>No confirmed matching images yet. Pending/error images are not negative results.</p>'}${allProperties}${allImages}<details><summary>Coverage and errors</summary><table><tr><th>Development</th><th>Status</th><th>Details</th></tr>${report.developments.map(d => `<tr><td><a href="${escape(d.url)}">${escape(d.name || d.url.split('/').at(-1))}</a></td><td>${escape(d.status)}</td><td>${escape(d.error || d.warning || '')}</td></tr>`).join('')}</table><pre>${escape(JSON.stringify(report.errors, null, 2))}</pre></details></html>`);
 await saveArtifact(`${folder}/index.html`, matchedPage(report));
 const csv = (values: unknown[]) => values.map(v => '"' + String(v ?? '').replaceAll('"', '""') + '"').join(',');
 await saveArtifact(`${folder}/properties.csv`, [csv(['development', 'house_type', 'bedrooms', 'price', 'url', 'plots', 'images', 'matched_images']), ...report.properties.map(p => csv([p.development, p.name, p.bedrooms, p.price, p.url, p.plots.map(v => v.number).join(';'), p.imageIds.length, p.imageIds.filter(id => imageMap.get(id)?.verdict?.matches).length]))].join('\n'));
 await saveArtifact(`${folder}/matches.csv`, [csv(['development', 'house_type', 'bedrooms', 'property_url', 'image_file', 'image_url', 'reason']), ...matched.flatMap(p => p.imageIds.map(id => imageMap.get(id)).filter(i => i?.verdict?.matches).map(i => csv([p.development, p.name, p.bedrooms, p.url, i!.path, i!.sourceUrl, i!.verdict!.reason])))].join('\n'));
}
