export const developers = [
 { slug: 'bellway', name: 'Bellway', website: 'https://www.bellway.co.uk', sitemap: '/developments-sitemap.xml' },
 { slug: 'cala', name: 'Cala', website: 'https://www.cala.co.uk', sitemap: '/sitemap.xml' },
 { slug: 'barratt', name: 'Barratt', website: 'https://www.barratthomes.co.uk', sitemap: '/sitemaps/sitemap-barratt-developments.xml' },
 { slug: 'taylor-wimpey', name: 'Taylor Wimpey', website: 'https://www.taylorwimpey.co.uk', sitemap: '/developments.xml' },
 { slug: 'david-wilson', name: 'David Wilson Homes', website: 'https://www.dwh.co.uk', sitemap: '/sitemap/' },
 { slug: 'miller-homes', name: 'Miller Homes', website: 'https://www.millerhomes.co.uk', sitemap: '/sitemaps.xml' },
 { slug: 'avant', name: 'Avant', website: 'https://www.avanthomes.co.uk', sitemap: '/sitemap.xml' },
 { slug: 'springfield', name: 'Springfield', website: 'https://www.springfield.co.uk', sitemap: '/sitemap.xml' },
 { slug: 'persimmon', name: 'Persimmon', website: 'https://www.persimmonhomes.com', sitemap: '/sitemap' },
 { slug: 'robertson-homes', name: 'Robertson Homes', website: 'https://www.robertsonhomes.co.uk', sitemap: '/sitemap_index.xml' },
 { slug: 'redrow', name: 'Redrow', website: 'https://www.redrow.co.uk', sitemap: '/sitemaps/sitemap-redrow-developments.xml' },
 { slug: 'berkeley-group', name: 'The Berkeley Group', website: 'https://www.berkeleygroup.co.uk', sitemap: '/sitemaps/sitemap-index' },
 { slug: 'crest-nicholson', name: 'Crest Nicholson', website: 'https://www.crestnicholson.com', sitemap: '/sitemap.xml' },
 { slug: 'lynch-homes', name: 'Lynch Homes', website: 'https://www.lynchhomes.co.uk', sitemap: '/sitemap_index.xml' },
 { slug: 'story-homes', name: 'Story Homes', website: 'https://www.storyhomes.co.uk', sitemap: '/sitemap_index.xml' },
 { slug: 'hill-group', name: 'Hill Group', website: 'https://www.hill.co.uk', sitemap: '/sitemap.xml' },
 { slug: 'tulloch-homes', name: 'Tulloch Homes', website: 'https://www.tulloch-homes.com', sitemap: '/homes-for-sale' },
 { slug: 'scotia-homes', name: 'Scotia Homes', website: 'https://www.scotia-homes.co.uk', sitemap: '/sitemap.xml' },
 { slug: 'bovis-homes', name: 'Bovis Homes', website: 'https://www.bovishomes.co.uk', sitemap: '/sitemap.xml' },
 { slug: 'linden-homes', name: 'Linden Homes', website: 'https://www.lindenhomes.co.uk', sitemap: '/sitemap.xml' },
 { slug: 'countryside-homes', name: 'Countryside Homes', website: 'https://www.countrysidehomes.com', sitemap: '/sitemap.xml' },
 { slug: 'bloor-homes', name: 'Bloor Homes', website: 'https://bloorhomes.com', sitemap: '/sitemap.xml' },
 { slug: 'keepmoat', name: 'Keepmoat', website: 'https://www.keepmoat.com', sitemap: '/sitemap' },
 { slug: 'gleeson', name: 'Gleeson Homes', website: 'https://gleesonhomes.co.uk', sitemap: '/developments/' },
 { slug: 'morris-homes', name: 'Morris Homes', website: 'https://www.morrishomes.co.uk', sitemap: '/development-sitemap.xml' },
 { slug: 'harron-homes', name: 'Harron Homes', website: 'https://www.harronhomes.com', sitemap: '/harron_developments-sitemap.xml' },
 { slug: 'anwyl-homes', name: 'Anwyl Homes', website: 'https://www.anwylhomes.co.uk', sitemap: '/development-sitemap.xml' },
 {slug:'castle-green-homes',name:'Castle Green Homes',website:'https://www.castlegreenhomes.uk',sitemap:'/our_developments-sitemap.xml'},
 {slug:'lovell',name:'Lovell Homes',website:'https://newhomes.lovell.co.uk',sitemap:'/sitemap.xml'},
 {slug:'wain-homes',name:'Wain Homes',website:'https://www.wainhomes.co.uk',sitemap:'/development-sitemap.xml'},
 {slug:'dandara',name:'Dandara',website:'https://www.dandara.com',sitemap:'/sitemap.xml'},
 {slug:'maguires-developments',name:'Maguires Developments',website:'https://www.m-d.co.uk',sitemap:'/sitemap.xml'},
 {slug:'bancon-homes',name:'Bancon Homes',website:'https://banconhomes.com',sitemap:'/sitemap.xml'},
 {slug:'ajc-homes',name:'AJC Homes',website:'https://ajcscotland.com',sitemap:'/developments'},
 {slug:'hayhill',name:'Hayhill Developments',website:'https://www.hayhilldevelopments.co.uk',sitemap:'/sitemap_index.xml'},
 {slug:'hopkins-homes',name:'Hopkins Homes',website:'https://www.hopkinshomes.co.uk',sitemap:'/sitemap-xml/'},
 {slug:'larkfleet-homes',name:'Larkfleet Homes',website:'https://allison-homes.co.uk',sitemap:'/development-sitemap.xml'},
] as const;
export type DeveloperSlug = typeof developers[number]['slug'];
export const crawlOrder: DeveloperSlug[] = developers.slice(3).map(d => d.slug);
