import * as bargate from './bargate/site-parser.js';
import * as larkfleet from './larkfleet/site-parser.js';
import * as hopkins from './hopkins/site-parser.js';
import * as maguires from './maguires/site-parser.js';
import * as wain from './wain/site-parser.js';
import * as hayhill from './hayhill/site-parser.js';
import * as ajc from './ajc/site-parser.js';
import * as bancon from './bancon/site-parser.js';
import * as dandara from './dandara/site-parser.js';
import * as lovell from './lovell/site-parser.js';
import * as castleGreen from './castle-green/site-parser.js';
import { createVistryParser } from './vistry/site-parser.js';
import * as bloor from './bloor/site-parser.js';
import * as keepmoat from './keepmoat/site-parser.js';
import * as gleeson from './gleeson/site-parser.js';
import * as morris from './morris/site-parser.js';
import * as harron from './harron/site-parser.js';
import * as anwyl from './anwyl/site-parser.js';
import * as tulloch from './tulloch/site-parser.js';
import * as scotia from './scotia/site-parser.js';
import * as robertson from './robertson/site-parser.js';
import * as persimmon from './persimmon/site-parser.js';
import * as springfield from './springfield/site-parser.js';
import * as avant from './avant/site-parser.js';
import * as miller from './miller/site-parser.js';
import { createSiteParser } from './barratt/site-parser.js';
import * as taylor from './taylor-wimpey/site-parser.js';
import * as bellway from './bellway/site-parser.js';
import * as barratt from './barratt/site-parser.js';
import * as cala from './cala/site-parser.js';
export function builderSite(slug='bellway') {
 if(slug==='bargate-homes')return {name:'Bargate Homes',slug,websiteUrl:'https://www.bargatehomes.co.uk',sitemap:'https://www.bargatehomes.co.uk/hbp_developments-sitemap.xml',...bargate};
 if(slug==='bellway')return {name:'Bellway',slug,websiteUrl:'https://www.bellway.co.uk',sitemap:'https://www.bellway.co.uk/developments-sitemap.xml',...bellway};
 if(slug==='cala')return {name:'Cala',slug,websiteUrl:'https://www.cala.co.uk',sitemap:'https://www.cala.co.uk/sitemap.xml',...cala};
 if(slug==='barratt')return {name:'Barratt',slug,websiteUrl:'https://www.barratthomes.co.uk',sitemap:'https://www.barratthomes.co.uk/sitemaps/sitemap-barratt-developments.xml',...barratt};
 if(slug==='taylor-wimpey')return {name:'Taylor Wimpey',slug,websiteUrl:'https://www.taylorwimpey.co.uk',sitemap:'https://www.taylorwimpey.co.uk/developments.xml',...taylor};
 if(slug==='david-wilson')return {name:'David Wilson Homes',slug,websiteUrl:'https://www.dwh.co.uk',sitemap:'https://www.dwh.co.uk/sitemap/',...createSiteParser('https://www.dwh.co.uk')};
 if(slug==='miller-homes')return {name:'Miller Homes',slug,websiteUrl:'https://www.millerhomes.co.uk',sitemap:'https://www.millerhomes.co.uk/sitemaps.xml',...miller};
 if(slug==='avant')return {name:'Avant',slug,websiteUrl:'https://www.avanthomes.co.uk',sitemap:'https://www.avanthomes.co.uk/sitemap.xml',...avant};
 if(slug==='springfield')return {name:'Springfield',slug,websiteUrl:'https://www.springfield.co.uk',sitemap:'https://www.springfield.co.uk/homes-for-sale',...springfield};
 if(slug==='persimmon')return {name:'Persimmon',slug,websiteUrl:'https://www.persimmonhomes.com',sitemap:'https://www.persimmonhomes.com/sitemap',...persimmon};
 if(slug==='robertson-homes')return {name:'Robertson Homes',slug,websiteUrl:'https://www.robertsonhomes.co.uk',sitemap:'https://www.robertsonhomes.co.uk/location-sitemap.xml',...robertson};
 if(slug==='redrow')return {name:'Redrow',slug,websiteUrl:'https://www.redrow.co.uk',sitemap:'https://www.redrow.co.uk/sitemaps/sitemap-redrow-developments.xml',...redrow};
 if(slug==='berkeley-group')return {name:'The Berkeley Group',slug,websiteUrl:'https://www.berkeleygroup.co.uk',sitemap:'https://www.berkeleygroup.co.uk/sitemaps/sitemap-developments',...berkeley};
 if(slug==='crest-nicholson')return {name:'Crest Nicholson',slug,websiteUrl:'https://www.crestnicholson.com',sitemap:'https://www.crestnicholson.com/sitemap.xml',...crest};
 if(slug==='lynch-homes')return {name:'Lynch Homes',slug,websiteUrl:'https://www.lynchhomes.co.uk',sitemap:'https://www.lynchhomes.co.uk/sitemap_index.xml',...lynch};
 if(slug==='story-homes')return {name:'Story Homes',slug,websiteUrl:'https://www.storyhomes.co.uk',sitemap:'https://www.storyhomes.co.uk/developments/',...story};
 if(slug==='hill-group')return {name:'Hill Group',slug,websiteUrl:'https://www.hill.co.uk',sitemap:'https://www.hill.co.uk/all-developments',...hill};
 if(slug==='tulloch-homes')return {name:'Tulloch Homes',slug,websiteUrl:'https://www.tulloch-homes.com',sitemap:'https://www.tulloch-homes.com/homes-for-sale',...tulloch};
 if(slug==='scotia-homes')return {name:'Scotia Homes',slug,websiteUrl:'https://www.scotia-homes.co.uk',sitemap:'https://www.scotia-homes.co.uk/sitemap.xml',...scotia};
 if(slug==='bovis-homes')return {name:'Bovis Homes',slug,websiteUrl:'https://www.bovishomes.co.uk',sitemap:'https://www.bovishomes.co.uk/sitemap.xml',...createVistryParser('https://www.bovishomes.co.uk')};
 if(slug==='linden-homes')return {name:'Linden Homes',slug,websiteUrl:'https://www.lindenhomes.co.uk',sitemap:'https://www.lindenhomes.co.uk/sitemap.xml',...createVistryParser('https://www.lindenhomes.co.uk')};
 if(slug==='countryside-homes')return {name:'Countryside Homes',slug,websiteUrl:'https://www.countrysidehomes.com',sitemap:'https://www.countrysidehomes.com/sitemap.xml',...createVistryParser('https://www.countrysidehomes.com')};
 if(slug==='bloor-homes')return {name:'Bloor Homes',slug,websiteUrl:'https://bloorhomes.com',sitemap:'https://bloorhomes.com/sitemap.xml',...bloor};
 if(slug==='keepmoat')return {name:'Keepmoat',slug,websiteUrl:'https://www.keepmoat.com',sitemap:'https://www.keepmoat.com/sitemap',...keepmoat};
 if(slug==='gleeson')return {name:'Gleeson Homes',slug,websiteUrl:'https://gleesonhomes.co.uk',sitemap:'https://gleesonhomes.co.uk/developments/',...gleeson};
 if(slug==='morris-homes')return {name:'Morris Homes',slug,websiteUrl:'https://www.morrishomes.co.uk',sitemap:'https://www.morrishomes.co.uk/development-sitemap.xml',...morris};
 if(slug==='harron-homes')return {name:'Harron Homes',slug,websiteUrl:'https://www.harronhomes.com',sitemap:'https://www.harronhomes.com/harron_developments-sitemap.xml',...harron};
 if(slug==='anwyl-homes')return {name:'Anwyl Homes',slug,websiteUrl:'https://www.anwylhomes.co.uk',sitemap:'https://www.anwylhomes.co.uk/development-sitemap.xml',...anwyl};
 if(slug==='castle-green-homes')return {name:'Castle Green Homes',slug,websiteUrl:'https://www.castlegreenhomes.uk',sitemap:'https://www.castlegreenhomes.uk/our_developments-sitemap.xml',...castleGreen};
 if(slug==='lovell')return {name:'Lovell Homes',slug,websiteUrl:'https://newhomes.lovell.co.uk',sitemap:'https://newhomes.lovell.co.uk/sitemap.xml',...lovell};
 if(slug==='wain-homes')return {name:'Wain Homes',slug,websiteUrl:'https://www.wainhomes.co.uk',sitemap:'https://www.wainhomes.co.uk/development-sitemap.xml',...wain};
 if(slug==='dandara')return {name:'Dandara',slug,websiteUrl:'https://www.dandara.com',sitemap:'https://www.dandara.com/sitemap.xml',...dandara};
 if(slug==='maguires-developments')return {name:'Maguires Developments',slug,websiteUrl:'https://www.m-d.co.uk',sitemap:'https://www.m-d.co.uk/sitemap.xml',...maguires};
 if(slug==='bancon-homes')return {name:'Bancon Homes',slug,websiteUrl:'https://banconhomes.com',sitemap:'https://banconhomes.com/sitemap.xml',...bancon};
 if(slug==='ajc-homes')return {name:'AJC Homes',slug,websiteUrl:'https://ajcscotland.com',sitemap:'https://ajcscotland.com/developments',...ajc};
 if(slug==='hayhill')return {name:'Hayhill Developments',slug,websiteUrl:'https://www.hayhilldevelopments.co.uk',sitemap:'https://www.hayhilldevelopments.co.uk/sitemap_index.xml',...hayhill};
 if(slug==='hopkins-homes')return {name:'Hopkins Homes',slug,websiteUrl:'https://www.hopkinshomes.co.uk',sitemap:'https://www.hopkinshomes.co.uk/sitemap-xml/',...hopkins};
 if(slug==='larkfleet-homes')return {name:'Larkfleet Homes',slug,websiteUrl:'https://allison-homes.co.uk',sitemap:'https://allison-homes.co.uk/development-sitemap.xml',...larkfleet};
 throw new Error('Unsupported builder.');
}
import * as redrow from './redrow/site-parser.js';
import * as berkeley from './berkeley/site-parser.js';
import * as crest from './crest/site-parser.js';

import * as lynch from './lynch/site-parser.js';

import * as story from './story/site-parser.js';

import * as hill from './hill/site-parser.js';
