'use client';
import {useRef,useId,useState,useMemo,lazy,Suspense} from 'react';
import Link from 'next/link';
import {useSavedLocation} from './location-preferences';
import {milesBetween,type SiteCard} from './site-filters';
import {NextCardImage} from './card-image';
import {optimizedImageSource} from './optimized-image-source';
const SiteMap=lazy(()=>import('./site-map').then(module=>({default:module.SiteMap})));
export interface BuildingDevelopment {key:string;name:string;href:string|null;town:string|null;latitude:number|null;longitude:number|null;price:string;developer:string;image:string|null;logo:string|null;logoBackground:string}
export function BuildingDevelopmentList({developments,buildingName}:{developments:BuildingDevelopment[];buildingName:string}){
 const dialog=useRef<HTMLDialogElement>(null),titleId=useId();
 const [open,setOpen]=useState(false),[active,setActive]=useState<string|null>(null),[sequence,setSequence]=useState(0),[unavailable,setUnavailable]=useState(false);
 const cardRefs=useRef(new Map<string,HTMLLIElement>());
 const location=useSavedLocation();
 const items=developments.map(item=>({...item,distance:location&&item.latitude!==null&&item.longitude!==null&&Number.isFinite(item.latitude)&&Number.isFinite(item.longitude)?milesBetween(location,{latitude:item.latitude,longitude:item.longitude}):null}));
 if(location)items.sort((a,b)=>(a.distance??Infinity)-(b.distance??Infinity)||a.name.localeCompare(b.name));
 const mapCards=useMemo(()=>developments.map(item=>({key:item.key,name:item.name,developer:item.developer,href:item.href??undefined,image:item.image??'',description:'',count:0,country:null,town:item.town,latitude:item.latitude??undefined,longitude:item.longitude??undefined,properties:[]} satisfies SiteCard)),[developments]);
 const select=(key:string,fromMap=false)=>{setActive(key);setSequence(value=>value+1);if(fromMap)cardRefs.current.get(key)?.scrollIntoView({block:'nearest',behavior:'smooth'});};
 return <><button type="button" className="development-set-location building-developments-trigger" aria-label={`View ${items.length} developments on a map`} aria-haspopup="dialog" onClick={()=>{setOpen(true);dialog.current?.showModal();}}>{items.length}<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" aria-hidden="true"><path d="m3 6 6-3 6 3 6-3v15l-6 3-6-3-6 3V6Z"/><path d="M9 3v15M15 6v15"/></svg></button><dialog ref={dialog} className="building-developments-dialog" aria-labelledby={titleId} onClose={()=>setOpen(false)} onClick={event=>{if(event.target===event.currentTarget){const bounds=event.currentTarget.getBoundingClientRect();if(event.clientX<bounds.left||event.clientX>bounds.right||event.clientY<bounds.top||event.clientY>bounds.bottom)dialog.current?.close();}}}><div className="building-developments-dialog-heading"><h2 id={titleId}>{buildingName} Developments</h2><button type="button" aria-label="Close developments" onClick={()=>dialog.current?.close()}>×</button></div><div className="building-developments-dialog-body"><ul className="building-developments-cards" aria-label="Developments">{items.map(item=><li ref={element=>{if(element)cardRefs.current.set(item.key,element);else cardRefs.current.delete(item.key);}} key={item.key} className={`collection-card building-development-card${active===item.key?' is-selected':''}`}><button type="button" className="building-development-select" aria-pressed={active===item.key} aria-label={`Highlight ${item.name} on map`} onClick={()=>select(item.key)}>{item.image?<div className="site-preview-photo"> <NextCardImage src={optimizedImageSource(item.image)} alt={item.name} width={400} height={300} sizes="(max-width: 700px) 35vw, 180px" loading="lazy"/>{item.logo&&<img className="development-builder-logo" src={item.logo} alt={`${item.developer} logo`} style={{background:item.logoBackground}} loading="lazy"/>}</div>:<div className="result-loading-visual"><i className="card-image-loading"/></div>}<div className="card-body"><h3>{item.name}</h3><p className="subtle">{item.town}{item.distance!==null?`${item.town?' · ':''}${item.distance.toFixed(1)} miles`:''}</p><p>{item.price==='Not available'?'Price not available':item.price}</p></div></button>{item.href&&<Link prefetch={false} className="building-development-link" href={item.href}>View Development →</Link>}</li>)}</ul><div className="building-developments-map">{open&&<Suspense fallback={<p role="status">Loading development map…</p>}><SiteMap cards={mapCards} simpleAttribution activeKey={active} focusSequence={sequence} onBoundsChange={()=>{}} onSelect={key=>select(key,true)} onUnavailable={()=>setUnavailable(true)}/></Suspense>}{unavailable&&<p role="status">Map unavailable. You can still browse the development cards.</p>}</div></div></dialog></>;
}
