'use client';
import {useEffect,useState} from 'react';
import {authClient} from '../auth/browser';
import type {ImageCategorisation} from '../reports/report';
interface Snapshot {builder:string;updatedAt:string;publication:string;development:string;groups:{development:string;buildingType:string;completed:number;failed:number;pending:number}[];images:{id:string;path:string;categorisation?:ImageCategorisation;model?:string;error?:string}[]}
export function Classifications(){
 const [selected,setSelected]=useState('');
 const [data,setData]=useState<{builders:string[];commit:string;reports:Snapshot[]}|null>(null),[error,setError]=useState('');
 useEffect(()=>{let alive=true,busy=false;async function refresh(){if(busy)return;busy=true;try{const client=await authClient();const {data:{session}}=await client.auth.getSession();if(!session){if(alive){setData(null);setError('Sign in with your owner account to view classifications.');}return;}const response=await fetch('/api/classifications'+(selected?'?builder='+encodeURIComponent(selected):''),{headers:{Authorization:'Bearer '+session.access_token},cache:'no-store'});if(!response.ok){if(alive)setData(null);throw new Error(response.status===403?'Access denied.':'Unable to load classifications.');}const result=await response.json();if(alive){setData(result);setError('');}}catch(e){if(alive)setError(e instanceof Error?e.message:'Unable to load classifications.');}finally{busy=false;}}void refresh();const timer=setInterval(()=>void refresh(),15000);return()=>{alive=false;clearInterval(timer);};},[selected]);
 return <main style={{padding:'2rem',maxWidth:1200,margin:'auto'}}><h1>Classifications</h1><p>Checks for updates every 15 seconds. New reports appear after deployment completes.</p>{error&&<p role="alert">{error}</p>}{data&&<><label>Builder <select value={selected||data.builders[0]||''} onChange={e=>{setSelected(e.target.value);setData(null);}}>{data.builders.map(b=><option key={b} value={b}>{b}</option>)}</select></label><p>Deployed commit: {data.commit}</p>{!data.reports.length&&<p>No classification runs have been published yet.</p>}{data.reports.map(report=><section key={report.builder}><h2>{report.builder}</h2><p>Updated {report.updatedAt} · Database: {report.publication} · Latest development: {report.development}</p><table><thead><tr><th>Development</th><th>Building type</th><th>Completed</th><th>Failed</th><th>Pending</th></tr></thead><tbody>{report.groups.map((g,i)=><tr key={i}><td>{g.development}</td><td>{g.buildingType}</td><td>{g.completed}</td><td>{g.failed}</td><td>{g.pending}</td></tr>)}</tbody></table><details><summary>Image classifications ({report.images.length})</summary>{report.images.map(image=><article key={image.id}><img loading="lazy" src={`/api/assets/${report.builder}/${image.path}`} alt="Classification preview" width={280}/><p>Model: {image.categorisation?.categorisationModel??image.model??'Not recorded'}</p><pre style={{whiteSpace:'pre-wrap'}}>{JSON.stringify(image.categorisation??{status:image.error?'failed':'pending',error:image.error},null,2)}</pre></article>)}</details></section>)}</>}</main>;
}
