'use client';
import {Children,useEffect,useRef,useState,type ReactNode} from 'react';
export function DirectoryFilters({children,className='',label='Directory filters',primaryCount=2}:{children:ReactNode;className?:string;label?:string;primaryCount?:number}){
 const items=Children.toArray(children).filter(Boolean),primary=items.slice(0,primaryCount),remaining=items.slice(primaryCount);
 const [mobile,setMobile]=useState(false),[open,setOpen]=useState(false);const dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{if(typeof window.matchMedia!=='function')return;const query=window.matchMedia('(max-width:900px)');const update=()=>{setMobile(query.matches);if(!query.matches)setOpen(false);};update();query.addEventListener('change',update);return()=>query.removeEventListener('change',update);},[]);
 useEffect(()=>{const element=dialog.current;if(!element)return;if(open){element.showModal();element.querySelectorAll('details').forEach(details=>details.open=true);}else if(element.open)element.close();},[open]);
 return <div className={`directory-filter-row ${className}`} role="search" aria-label={label}>{primary}{!mobile&&<div className="directory-secondary-filters">{remaining}</div>}{mobile&&remaining.length>0&&<><button className="directory-drawer-toggle" type="button" onClick={()=>setOpen(true)} aria-label="All filters" aria-haspopup="dialog">☷</button><dialog ref={dialog} className="directory-filter-drawer" onClose={()=>setOpen(false)} onCancel={()=>setOpen(false)} aria-label={label}><div className="directory-drawer-heading"><h2>Filters</h2><button type="button" onClick={()=>setOpen(false)} aria-label="Close filters">×</button></div><div className="directory-drawer-fields">{remaining}</div><button type="button" className="directory-drawer-done" onClick={()=>setOpen(false)}>Show results</button></dialog></>}</div>;
}
