-- Original image metadata and raw extracted labels remain unchanged.
create table showhome_web.furnishing_category_mappings (
 source_name text primary key,
 category_name text,
 decision text not null default 'pending' check(decision in ('mapped','excluded','pending')),
 check (source_name=lower(trim(source_name)) and source_name<>''),
 check (category_name is null or category_name=lower(trim(category_name)) and category_name<>''),
 check ((decision='mapped')=(category_name is not null))
);
create index furnishing_category_mapping_category on showhome_web.furnishing_category_mappings(category_name,source_name) where category_name is not null;
insert into showhome_web.furnishing_category_mappings(source_name,category_name,decision) values
('accent chair','accent chairs','mapped'),
('accent wall','accent walls','mapped'),
('accessories',NULL,'excluded'),
('air conditioner',NULL,'excluded'),
('air conditioning unit',NULL,'excluded'),
('air freshener','air fresheners','mapped'),
('airplane decals','airplane decals','mapped'),
('airplane models','airplane models','mapped'),
('alarm clock','alarm clocks','mapped'),
('amplifier','amplifiers','mapped'),
('appliance',NULL,'excluded'),
('appliances',NULL,'excluded'),
('apron','aprons','mapped'),
('aprons','aprons','mapped'),
('arched mirror','mirrors','mapped'),
('arched wall panel','wall panelling','mapped'),
('area rug','rugs','mapped'),
('armchair','armchairs','mapped'),
('armchairs','armchairs','mapped'),
('arrow',NULL,'excluded'),
('art','artwork','mapped'),
('art easel','art easels','mapped'),
('artichokes',NULL,'excluded'),
('artificial plants','plants','mapped'),
('artwork','artwork','mapped'),
('artwork frame','artwork','mapped'),
('artworks','artwork','mapped'),
('asparagus',NULL,'excluded'),
('backpack',NULL,'excluded'),
('backrest','backrests','mapped'),
('backsplash','splashbacks','mapped'),
('bag',NULL,'excluded'),
('bags',NULL,'excluded'),
('balance bike','balance bikes','mapped'),
('balcony','balconies','mapped'),
('balcony door','balcony doors','mapped'),
('balcony doors','balcony doors','mapped'),
('balcony railing','balcony railings','mapped'),
('ball','balls','mapped'),
('ball pit','ball pits','mapped'),
('balustrade','balustrades','mapped'),
('bamboo divider','bamboo dividers','mapped'),
('bamboo screen','bamboo screens','mapped'),
('banister','banisters','mapped'),
('banner','banners','mapped'),
('banners','banners','mapped'),
('bar','bars','mapped'),
('bar cart','bar carts','mapped'),
('bar counter','bar counters','mapped'),
('bar stool','bar stools','mapped'),
('bar stools','bar stools','mapped'),
('barrel','barrels','mapped'),
('barstool','bar stools','mapped'),
('barstools','bar stools','mapped'),
('base cabinet','kitchen cabinets','mapped'),
('baseboard','baseboards','mapped'),
('baseboards','baseboards','mapped'),
('basin','bathroom basins','mapped'),
('basin unit','vanity units','mapped'),
('basket','baskets','mapped'),
('basketball hoop','basketball hoops','mapped'),
('baskets','baskets','mapped'),
('bath','bath tubs','mapped'),
('bath accessories',NULL,'excluded'),
('bath basket','baskets','mapped'),
('bath brush','bath brushes','mapped'),
('bath caddy','bath trays','mapped'),
('bath candle','candles','mapped'),
('bath items',NULL,'excluded'),
('bath lotion',NULL,'excluded'),
('bath mat','bath mats','mapped'),
('bath oil',NULL,'excluded'),
('bath products',NULL,'excluded'),
('bath reed diffuser','reed diffusers','mapped'),
('bath salts',NULL,'excluded'),
('bath scrubber','bath scrubbers','mapped'),
('bath soap',NULL,'excluded'),
('bath sponge','bath sponges','mapped'),
('bath towel','towels','mapped'),
('bath towels','towels','mapped'),
('bath toys','bath toys','mapped'),
('bath tray','bath trays','mapped'),
('bathrobe',NULL,'excluded'),
('bathroom',NULL,'excluded'),
('bathroom accessories',NULL,'excluded'),
('bathroom bottles','bathroom bottles','mapped'),
('bathroom cabinet','bathroom cabinets','mapped'),
('bathroom cabinet frame','bathroom cabinets','mapped'),
('bathroom ceiling',NULL,'excluded'),
('bathroom door','bathroom doors','mapped'),
('bathroom door frame','bathroom doors','mapped'),
('bathroom fixtures','bathroom fixtures','mapped'),
('bathroom floor','bathroom floors','mapped'),
('bathroom mat','bath mats','mapped'),
('bathroom mirror','mirrors','mapped'),
('bathroom mirror frame','mirrors','mapped'),
('bathroom products',NULL,'excluded'),
('bathroom rack','bathroom racks','mapped'),
('bathroom shelf','bathroom shelfs','mapped'),
('bathroom shelf frame','bathroom shelfs','mapped'),
('bathroom shower','bathroom showers','mapped'),
('bathroom sink','bathroom basins','mapped'),
('bathroom sink frame','bathroom basins','mapped'),
('bathroom tiles','bathroom tiles','mapped'),
('bathroom toilet','bathroom toilets','mapped'),
('bathroom toilet frame','bathroom toilets','mapped'),
('bathroom towel','towels','mapped'),
('bathroom towel rack','bathroom towel racks','mapped'),
('bathroom towels','towels','mapped'),
('bathroom wall','bathroom walls','mapped'),
('bathtub','bath tubs','mapped'),
('bean bag','bean bags','mapped'),
('bean bag chair','bean bags','mapped'),
('beanbag','bean bags','mapped'),
('beanbag chair','bean bags','mapped'),
('bear rug','bear rugs','mapped'),
('bed','beds','mapped'),
('bed base',NULL,'excluded'),
('bed canopy','bed canopies','mapped'),
('bed cushions','cushions','mapped'),
('bed frame','beds','mapped'),
('bed ottoman','bed ottomans','mapped'),
('bedding','bedding','mapped'),
('beds','beds','mapped'),
('bedside cabinet','bedside cabinets','mapped'),
('bedside chair','bedside chairs','mapped'),
('bedside lamp','bedside lamps','mapped'),
('bedside shelf','bedside shelfs','mapped'),
('bedside table','bedside tables','mapped'),
('bedside tables','bedside tables','mapped'),
('bedspread','bedspreads','mapped'),
('bench','benches','mapped'),
('bench chair','bench chairs','mapped'),
('bench cover','bench covers','mapped'),
('bench cushion','bench cushions','mapped'),
('benches','benches','mapped'),
('bi-fold doors','bi-fold doors','mapped'),
('bicycle','bicycles','mapped'),
('bicycle rack','bicycle racks','mapped'),
('bifold door','bifold doors','mapped'),
('bin','bins','mapped'),
('binder','binders','mapped'),
('bird figurine','bird figurines','mapped'),
('blackboard','blackboards','mapped'),
('blanket','blankets','mapped'),
('blankets','blankets','mapped'),
('blind','blinds','mapped'),
('blinds','blinds','mapped'),
('board','boards','mapped'),
('boat','boats','mapped'),
('boiler',NULL,'excluded'),
('book','books','mapped'),
('bookcase','bookcases','mapped'),
('books','books','mapped'),
('bookshelf','bookcases','mapped'),
('bookshelf contents','bookshelf contents','mapped'),
('bookshelves','bookcases','mapped'),
('boot',NULL,'excluded'),
('boots',NULL,'excluded'),
('bottle','bottles','mapped'),
('bottles','bottles','mapped'),
('bouclé armchair','armchairs','mapped'),
('boucle chair','chairs','mapped'),
('bouclé chairs','chairs','mapped'),
('bowl','bowls','mapped'),
('bowls','bowls','mapped'),
('box','boxes','mapped'),
('boxes','boxes','mapped'),
('bread',NULL,'excluded'),
('bread bin','bread bins','mapped'),
('breadboard','chopping boards','mapped'),
('breakfast bar','breakfast bars','mapped'),
('broad wall panel','broad wall panels','mapped'),
('broadboards','broadboards','mapped'),
('broadwall','broadwalls','mapped'),
('broom',NULL,'excluded'),
('brush','brushes','mapped'),
('brushes','brushes','mapped'),
('bucket','buckets','mapped'),
('built-in niche','built-in niches','mapped'),
('built-in shelving','shelving','mapped'),
('bunk bed','bunk beds','mapped'),
('bunting','buntings','mapped'),
('cabinet','cabinets','mapped'),
('cabinet handles','cabinet handles','mapped'),
('cabinet knobs','cabinet knobs','mapped'),
('cabinetry','kitchen cabinets','mapped'),
('cabinets','cabinets','mapped'),
('cactus','cactus','mapped'),
('cactus decoration','cactus decorations','mapped'),
('caddy','caddies','mapped'),
('calendar','calendars','mapped'),
('camera','cameras','mapped'),
('candelabra','candelabras','mapped'),
('candelabrum','candelabrums','mapped'),
('candle','candles','mapped'),
('candle holder','candle holders','mapped'),
('candle holders','candle holders','mapped'),
('candle lantern','candle lanterns','mapped'),
('candles','candles','mapped'),
('candlestick','candlesticks','mapped'),
('candlesticks','candlesticks','mapped'),
('cane chair','chairs','mapped'),
('canister','canisters','mapped'),
('canisters','canisters','mapped'),
('canopy','canopies','mapped'),
('cap',NULL,'excluded'),
('caps',NULL,'excluded'),
('carafe','carafes','mapped'),
('carpet','carpets','mapped'),
('carrots',NULL,'excluded'),
('cart','carts','mapped'),
('cat bed','cat beds','mapped'),
('cat tree','cat trees','mapped'),
('ceiling',NULL,'excluded'),
('ceiling decor',NULL,'excluded'),
('ceiling decoration',NULL,'excluded'),
('ceiling decorations',NULL,'excluded'),
('ceiling fan',NULL,'excluded'),
('ceiling fixture','ceiling lights','mapped'),
('ceiling lamp','ceiling lights','mapped'),
('ceiling light','ceiling lights','mapped'),
('ceiling light fixture','ceiling lights','mapped'),
('ceiling lights','ceiling lights','mapped'),
('ceiling molding',NULL,'excluded'),
('ceiling mural',NULL,'excluded'),
('cello','cellos','mapped'),
('ceramic bowl','bowls','mapped'),
('ceramic bowls','bowls','mapped'),
('ceramic ornaments','ornaments','mapped'),
('ceramicware','ceramicwares','mapped'),
('chair','chairs','mapped'),
('chairs','chairs','mapped'),
('chaise longue','chaise longues','mapped'),
('chaise lounge','chaise lounges','mapped'),
('chalkboard','chalkboards','mapped'),
('chalkboard wall hanging','chalkboard wall hangings','mapped'),
('champagne bottle','champagne bottles','mapped'),
('champagne bucket','champagne buckets','mapped'),
('chandelier','chandeliers','mapped'),
('chandeliers','chandeliers','mapped'),
('changing table','changing tables','mapped'),
('chess set','chess sets','mapped'),
('chest','chests','mapped'),
('chest of drawers','chest of drawers','mapped'),
('chopping board','chopping boards','mapped'),
('chopping boards','chopping boards','mapped'),
('circular armchair','circular armchairs','mapped'),
('circular coffee table','circular coffee tables','mapped'),
('circular ottoman','circular ottomans','mapped'),
('circular rug','circular rugs','mapped'),
('circular sofa','circular sofas','mapped'),
('circular table','circular tables','mapped'),
('circular wooden board','circular wooden boards','mapped'),
('clear chair','clear chairs','mapped'),
('clock','clocks','mapped'),
('clocks','clocks','mapped'),
('closet','closets','mapped'),
('closet door','closet doors','mapped'),
('closet drawer','closet drawers','mapped'),
('closet rack','closet racks','mapped'),
('closet rod','closet rods','mapped'),
('closet shelf','closet shelfs','mapped'),
('closet shelves','closet shelves','mapped'),
('cloth bag','cloth bags','mapped'),
('clothes',NULL,'excluded'),
('clothes rack','clothes racks','mapped'),
('clothes rail','clothes rails','mapped'),
('clothing',NULL,'excluded'),
('clothing hanger','clothing hangers','mapped'),
('clothing rack','clothing racks','mapped'),
('clothing rail','clothing rails','mapped'),
('cloud decoration','cloud decorations','mapped'),
('cloud light','cloud lights','mapped'),
('cloud shelves','cloud shelves','mapped'),
('coat',NULL,'excluded'),
('coat hook','coat hooks','mapped'),
('coat hooks','coat hooks','mapped'),
('coat rack','coat racks','mapped'),
('coatrack','coatracks','mapped'),
('coffee cup','coffee cups','mapped'),
('coffee machine','coffee machines','mapped'),
('coffee maker','coffee makers','mapped'),
('coffee menu sign','coffee menu signs','mapped'),
('coffee mug','coffee mugs','mapped'),
('coffee mugs','coffee mugs','mapped'),
('coffee pot','coffee pots','mapped'),
('coffee table','coffee tables','mapped'),
('coffee tables','coffee tables','mapped'),
('colander','colanders','mapped'),
('compass','compass','mapped'),
('computer','computers','mapped'),
('computer monitor','computer monitors','mapped'),
('cones','cones','mapped'),
('console','consoles','mapped'),
('console table','console tables','mapped'),
('container','containers','mapped'),
('containers','containers','mapped'),
('controller','controllers','mapped'),
('controller decor','controller decors','mapped'),
('cookbook','cookbooks','mapped'),
('cooker hood','cooker hoods','mapped'),
('cookies',NULL,'excluded'),
('cooktop','cooktops','mapped'),
('cookware','cookwares','mapped'),
('corgi plush','corgi plushes','mapped'),
('corkboard','corkboards','mapped'),
('corn',NULL,'excluded'),
('costume','costumes','mapped'),
('cot','cots','mapped'),
('couch','sofas','mapped'),
('couch cushions','cushions','mapped'),
('counter','counters','mapped'),
('countertop','worktops','mapped'),
('countertops','worktops','mapped'),
('crate','crates','mapped'),
('crib','cribs','mapped'),
('cricket bat','cricket bats','mapped'),
('crocodile head','crocodile heads','mapped'),
('croissants',NULL,'excluded'),
('cross-back chairs','cross-back chairs','mapped'),
('crossback chairs','crossback chairs','mapped'),
('cup','cups','mapped'),
('cups','cups','mapped'),
('cups and plates','cups and plates','mapped'),
('curtain','curtains','mapped'),
('curtain box','curtain boxes','mapped'),
('curtain rod','curtain rods','mapped'),
('curtain valance','curtain valances','mapped'),
('curtains','curtains','mapped'),
('cushion','cushions','mapped'),
('cushioned chairs','cushioned chairs','mapped'),
('cushions','cushions','mapped'),
('cutlery','cutlery','mapped'),
('cutout','cutouts','mapped'),
('cutting board','chopping boards','mapped'),
('cutting boards','chopping boards','mapped'),
('cylindrical containers','cylindrical containers','mapped'),
('dark wood',NULL,'excluded'),
('dark wood chairs','chairs','mapped'),
('daybed','daybeds','mapped'),
('decanter','decanters','mapped'),
('deck','decks','mapped'),
('deck chair','deck chairs','mapped'),
('decor',NULL,'excluded'),
('decoration',NULL,'excluded'),
('decorations',NULL,'excluded'),
('decorative bag',NULL,'excluded'),
('decorative ball','balls','mapped'),
('decorative balls','balls','mapped'),
('decorative basket','baskets','mapped'),
('decorative bird','birds','mapped'),
('decorative birds','birds','mapped'),
('decorative board','boards','mapped'),
('decorative bottle','bottles','mapped'),
('decorative bottles','bottles','mapped'),
('decorative bowl','bowls','mapped'),
('decorative bowls','bowls','mapped'),
('decorative box','boxes','mapped'),
('decorative boxes','boxes','mapped'),
('decorative branch','branches','mapped'),
('decorative branches','branches','mapped'),
('decorative butterfly','butterflies','mapped'),
('decorative cage','cages','mapped'),
('decorative container','containers','mapped'),
('decorative containers','containers','mapped'),
('decorative cup','cups','mapped'),
('decorative cushions','cushions','mapped'),
('decorative fan','fans','mapped'),
('decorative figurine','ornaments','mapped'),
('decorative fish','fishes','mapped'),
('decorative flags','flags','mapped'),
('decorative flower','flowers','mapped'),
('decorative flowers','flowers','mapped'),
('decorative fork','forks','mapped'),
('decorative frame','frames','mapped'),
('decorative grass','grass','mapped'),
('decorative heart','hearts','mapped'),
('decorative item','items','mapped'),
('decorative items','items','mapped'),
('decorative jar','jars','mapped'),
('decorative jars','jars','mapped'),
('decorative knife','knifes','mapped'),
('decorative knot','knots','mapped'),
('decorative lamp','lamps','mapped'),
('decorative lamp base','lamp bases','mapped'),
('decorative lanterns','lanterns','mapped'),
('decorative leaf','leafs','mapped'),
('decorative leaves','leaves','mapped'),
('decorative letters','letters','mapped'),
('decorative light fixture','light fixtures','mapped'),
('decorative mirror','mirrors','mapped'),
('decorative object','objects','mapped'),
('decorative objects','objects','mapped'),
('decorative orb','orbs','mapped'),
('decorative ornament','ornaments','mapped'),
('decorative panel','panels','mapped'),
('decorative piece','pieces','mapped'),
('decorative pieces','pieces','mapped'),
('decorative pillow','pillows','mapped'),
('decorative pillows','pillows','mapped'),
('decorative plant','plants','mapped'),
('decorative plant pot','plant pots','mapped'),
('decorative plants','plants','mapped'),
('decorative plate','plates','mapped'),
('decorative plates','plates','mapped'),
('decorative pots','pots','mapped'),
('decorative pumpkin','pumpkins','mapped'),
('decorative reed diffuser','reed diffusers','mapped'),
('decorative ring','rings','mapped'),
('decorative sculpture','sculptures','mapped'),
('decorative sculptures','sculptures','mapped'),
('decorative shelf','shelving','mapped'),
('decorative shell','shells','mapped'),
('decorative shoes',NULL,'excluded'),
('decorative sign','signs','mapped'),
('decorative sphere','spheres','mapped'),
('decorative spoon','spoons','mapped'),
('decorative star','stars','mapped'),
('decorative stars','stars','mapped'),
('decorative sticks','sticks','mapped'),
('decorative throw','throws','mapped'),
('decorative tile','tiles','mapped'),
('decorative tray','trays','mapped'),
('decorative tree','trees','mapped'),
('decorative vase','vases','mapped'),
('decorative vases','vases','mapped'),
('decorative wall art','wall arts','mapped'),
('decorative wall clock','wall clocks','mapped'),
('decorative wall decals','wall decals','mapped'),
('decorative wall hanging','wall hangings','mapped'),
('decorative wall hangings','wall hangings','mapped'),
('decorative wall mount','wall mounts','mapped'),
('decorative wall panel','wall panelling','mapped'),
('decorative wall piece','wall pieces','mapped'),
('decorative window fixture','window fixtures','mapped'),
('deer head ornament','deer head ornaments','mapped'),
('desk','desks','mapped'),
('desk chair','desk chairs','mapped'),
('desk organizer','desk organizers','mapped'),
('dice','dices','mapped'),
('diffuser','reed diffusers','mapped'),
('dining bench','dining benches','mapped'),
('dining chair','dining chairs','mapped'),
('dining chairs','dining chairs','mapped'),
('dining table','dining tables','mapped'),
('disco ball','disco balls','mapped'),
('dish rack','dish racks','mapped'),
('dishwasher','dishwashers','mapped'),
('dispenser','dispensers','mapped'),
('display cabinet','display cabinets','mapped'),
('dog','dogs','mapped'),
('dog bed','dog beds','mapped'),
('dog bowls','dog bowls','mapped'),
('dog figurine','dog figurines','mapped'),
('dog food container','dog food containers','mapped'),
('dog leash','dog leashes','mapped'),
('dog statue','dog statues','mapped'),
('doll','dolls','mapped'),
('doll pram','doll prams','mapped'),
('dollhouse','dollhouses','mapped'),
('door','doors','mapped'),
('door casing','door casings','mapped'),
('door frame','doors','mapped'),
('door frames','door frames','mapped'),
('door handle','door handles','mapped'),
('door hinge','door hinges','mapped'),
('door jamb','door jambs','mapped'),
('door latch','door latches','mapped'),
('door panel','door panels','mapped'),
('door seal','door seals','mapped'),
('door sill','door sills','mapped'),
('door stop','door stops','mapped'),
('door threshold','door thresholds','mapped'),
('door trim','door trims','mapped'),
('door window','door windows','mapped'),
('doorframe','doorframes','mapped'),
('doormat','doormats','mapped'),
('doors','doors','mapped'),
('doorway',NULL,'excluded'),
('doorways',NULL,'excluded'),
('double door','double doors','mapped'),
('drain',NULL,'excluded'),
('drawer','drawers','mapped'),
('drawer fronts','drawer fronts','mapped'),
('drawer unit','drawer units','mapped'),
('drawers','drawers','mapped'),
('drawings','drawings','mapped'),
('dreamcatcher','dreamcatchers','mapped'),
('dress',NULL,'excluded'),
('dresser','dressers','mapped'),
('dressing stool','dressing stools','mapped'),
('dressing table','dressing tables','mapped'),
('drinks','drinks','mapped'),
('dry riser outlet box',NULL,'excluded'),
('dryer','dryers','mapped'),
('duffel bag','duffel bags','mapped'),
('dumbbell rack','dumbbell racks','mapped'),
('dumbbells','dumbbells','mapped'),
('dust mop',NULL,'excluded'),
('duvet','duvets','mapped'),
('easel','easels','mapped'),
('electrical outlet',NULL,'excluded'),
('elephant figurine','elephant figurines','mapped'),
('elevator','elevators','mapped'),
('elevator control panel','elevator control panels','mapped'),
('en suite bathroom',NULL,'excluded'),
('entertainment center','tv units','mapped'),
('entertainment unit','tv units','mapped'),
('exercise ball','exercise balls','mapped'),
('exercise balls','exercise balls','mapped'),
('exercise bike','exercise bikes','mapped'),
('exercise equipment','exercise equipments','mapped'),
('exercise mat','exercise mats','mapped'),
('exhaust fan','exhaust fans','mapped'),
('exhaust hood','exhaust hoods','mapped'),
('exit sign',NULL,'excluded'),
('extractor','extractors','mapped'),
('extractor fan','extractor fans','mapped'),
('extractor hood','extractor hoods','mapped'),
('fabric',NULL,'excluded'),
('fabric canopy','canopies','mapped'),
('fabric chair','chairs','mapped'),
('fabric chairs','chairs','mapped'),
('fairy lights','fairy lights','mapped'),
('fan','fans','mapped'),
('faucet','faucets','mapped'),
('faucets','faucets','mapped'),
('feather decor','feather decors','mapped'),
('feeder','feeders','mapped'),
('fence','fences','mapped'),
('figurine','ornaments','mapped'),
('file holder','file holders','mapped'),
('fire extinguisher',NULL,'excluded'),
('fire pit','fire pits','mapped'),
('fire place','fire places','mapped'),
('fire truck cabinet','fire truck cabinets','mapped'),
('fireplace','fireplaces','mapped'),
('fireplace mantel','fireplace mantels','mapped'),
('fireplace screen','fireplace screens','mapped'),
('first aid bin','first aid bins','mapped'),
('fish decorations','fish decorations','mapped'),
('fixed surfaces',NULL,'excluded'),
('fixture',NULL,'excluded'),
('flag','flags','mapped'),
('flags','flags','mapped'),
('floor',NULL,'excluded'),
('floor cushion','floor cushions','mapped'),
('floor lamp','floor lamps','mapped'),
('floor lamps','floor lamps','mapped'),
('floor mat','floor mats','mapped'),
('floor rug','rugs','mapped'),
('floor tile','floor tiles','mapped'),
('floor tiles','floor tiles','mapped'),
('floor-mounted cabinet','floor-mounted cabinets','mapped'),
('flooring','flooring','mapped'),
('floral wreath','floral wreaths','mapped'),
('flower','flowers','mapped'),
('flower arrangement','flower arrangements','mapped'),
('flower garland','flower garlands','mapped'),
('flower vase','flower vases','mapped'),
('flowers','flowers','mapped'),
('fluffy chair','fluffy chairs','mapped'),
('flush plate','flush plates','mapped'),
('football','footballs','mapped'),
('footstool','footstools','mapped'),
('footstools','footstools','mapped'),
('fork','forks','mapped'),
('forks','forks','mapped'),
('frame','frames','mapped'),
('framed art','artwork','mapped'),
('framed artwork','artwork','mapped'),
('framed photos','framed photos','mapped'),
('framed picture','artwork','mapped'),
('framed pictures','artwork','mapped'),
('framed poster','framed posters','mapped'),
('framed prints','artwork','mapped'),
('framed quote','framed quotes','mapped'),
('framed sign','framed signs','mapped'),
('frames','frames','mapped'),
('french door','french doors','mapped'),
('french doors','french doors','mapped'),
('fridge','fridges','mapped'),
('fruit',NULL,'excluded'),
('fruit basket','fruit baskets','mapped'),
('fruit bowl','fruit bowls','mapped'),
('fruit stand','fruit stands','mapped'),
('fruits',NULL,'excluded'),
('furnishing',NULL,'excluded'),
('furniture',NULL,'excluded'),
('furry cushion','furry cushions','mapped'),
('game board','game boards','mapped'),
('game controller','game controllers','mapped'),
('gaming chair','gaming chairs','mapped'),
('garage door','garage doors','mapped'),
('garland','garlands','mapped'),
('gift','gifts','mapped'),
('gift box','gift boxes','mapped'),
('giraffe','giraffes','mapped'),
('giraffe figurine','giraffe figurines','mapped'),
('giraffe head','giraffe heads','mapped'),
('giraffe toy','giraffe toies','mapped'),
('glass','glass','mapped'),
('glass bottle','bottles','mapped'),
('glass cabinet','cabinets','mapped'),
('glass coffee table','coffee tables','mapped'),
('glass dining table','dining tables','mapped'),
('glass door','doors','mapped'),
('glass doors','doors','mapped'),
('glass jar','jars','mapped'),
('glass jars','jars','mapped'),
('glass partition','partitions','mapped'),
('glass railing','railings','mapped'),
('glass screen','screens','mapped'),
('glass shower screen','shower screens','mapped'),
('glass table','tables','mapped'),
('glass vase','vases','mapped'),
('glasses','glasses','mapped'),
('glassware','glasswares','mapped'),
('glassware stand','glassware stands','mapped'),
('globe','globes','mapped'),
('gloves',NULL,'excluded'),
('golf bag','golf bags','mapped'),
('golf clubs','golf clubs','mapped'),
('golf mat','golf mats','mapped'),
('grand piano','grand pianos','mapped'),
('grater','graters','mapped'),
('grid','grids','mapped'),
('grid wall organizer','grid wall organizers','mapped'),
('grid wall panel','grid wall panels','mapped'),
('growth chart','growth charts','mapped'),
('guitar','guitars','mapped'),
('gym bag','gym bags','mapped'),
('hairbrush','hairbrushes','mapped'),
('hallway',NULL,'excluded'),
('hammock','hammocks','mapped'),
('hand',NULL,'excluded'),
('hand soap','hand soaps','mapped'),
('hand soap dispenser','hand soap dispensers','mapped'),
('hand towel','towels','mapped'),
('handbag',NULL,'excluded'),
('handle','handles','mapped'),
('handles','handles','mapped'),
('handrail','handrails','mapped'),
('hanger','hangers','mapped'),
('hangers','hangers','mapped'),
('hanging bag','hanging bags','mapped'),
('hanging bags','hanging bags','mapped'),
('hanging chair','hanging chairs','mapped'),
('hanging clothes','hanging clothes','mapped'),
('hanging clothes rack','hanging clothes racks','mapped'),
('hanging coat','hanging coats','mapped'),
('hanging decoration','hanging decorations','mapped'),
('hanging garment','hanging garments','mapped'),
('hanging hat','hanging hats','mapped'),
('hanging hooks','hanging hooks','mapped'),
('hanging lamp','pendant lights','mapped'),
('hanging lamps','pendant lights','mapped'),
('hanging light','pendant lights','mapped'),
('hanging light fixture','pendant lights','mapped'),
('hanging plant','hanging plants','mapped'),
('hanging rack','hanging racks','mapped'),
('hanging rail','hanging rails','mapped'),
('hanging range hood','hanging range hoods','mapped'),
('hat',NULL,'excluded'),
('hat rack','hat racks','mapped'),
('hat stand','hat stands','mapped'),
('hats',NULL,'excluded'),
('headboard','headboards','mapped'),
('headboard net','headboard nets','mapped'),
('headboard wall','headboard walls','mapped'),
('headboards','headboards','mapped'),
('headphones','headphones','mapped'),
('heart decoration','heart decorations','mapped'),
('heart ornament','heart ornaments','mapped'),
('heated towel rail','heated towel rails','mapped'),
('heater','heaters','mapped'),
('heating radiator','heating radiators','mapped'),
('heating unit',NULL,'excluded'),
('helmet',NULL,'excluded'),
('high chair','high chairs','mapped'),
('hob','hobs','mapped'),
('hockey stick','hockey sticks','mapped'),
('hood','hoods','mapped'),
('hook','hooks','mapped'),
('hook rail','hook rails','mapped'),
('hooks','hooks','mapped'),
('horse head ornament','horse head ornaments','mapped'),
('horse ornament','horse ornaments','mapped'),
('horse statue','horse statues','mapped'),
('hourglass','hourglass','mapped'),
('hula hoop','hula hoops','mapped'),
('ice bucket','ice buckets','mapped'),
('intercom',NULL,'excluded'),
('island','islands','mapped'),
('island table','island tables','mapped'),
('jacket',NULL,'excluded'),
('jar','jars','mapped'),
('jars','jars','mapped'),
('jersey','jerseys','mapped'),
('jug','jugs','mapped'),
('jugs','jugs','mapped'),
('kettle','kettles','mapped'),
('keyboard','keyboards','mapped'),
('kitchen',NULL,'excluded'),
('kitchen appliances','kitchen appliances','mapped'),
('kitchen backsplash','splashbacks','mapped'),
('kitchen cabinet','kitchen cabinets','mapped'),
('kitchen cabinets','kitchen cabinets','mapped'),
('kitchen chairs','kitchen chairs','mapped'),
('kitchen counter','worktops','mapped'),
('kitchen countertop','worktops','mapped'),
('kitchen countertops','worktops','mapped'),
('kitchen decor','kitchen decors','mapped'),
('kitchen faucet','kitchen faucets','mapped'),
('kitchen hood','kitchen hoods','mapped'),
('kitchen island','kitchen islands','mapped'),
('kitchen island stools','bar stools','mapped'),
('kitchen scale','kitchen scales','mapped'),
('kitchen sink','kitchen sinks','mapped'),
('kitchen tools','kitchen tools','mapped'),
('kitchen unit','kitchen cabinets','mapped'),
('kitchen units','kitchen cabinets','mapped'),
('kitchen utensils','kitchen utensils','mapped'),
('kitchenette',NULL,'excluded'),
('kitchenware','kitchenwares','mapped'),
('knife','knifes','mapped'),
('knife block','knife blocks','mapped'),
('knitted ottoman','knitted ottomans','mapped'),
('knives','knives','mapped'),
('knobs','knobs','mapped'),
('label',NULL,'excluded'),
('ladder','ladders','mapped'),
('ladder mirror','ladder mirrors','mapped'),
('ladder rack','ladder racks','mapped'),
('ladder shelf','ladder shelfs','mapped'),
('lamp','lamps','mapped'),
('lamp base','lamp bases','mapped'),
('lamp bases','lamp bases','mapped'),
('lamp shade','lamp shades','mapped'),
('lamps','lamps','mapped'),
('lampshade','lampshades','mapped'),
('lampshades','lampshades','mapped'),
('lantern','lanterns','mapped'),
('lanterns','lanterns','mapped'),
('laptop','laptops','mapped'),
('laptops','laptops','mapped'),
('laundry bag','laundry bags','mapped'),
('laundry basket','laundry baskets','mapped'),
('laundry bin','laundry bins','mapped'),
('lawn','lawns','mapped'),
('leather',NULL,'excluded'),
('leather chair','chairs','mapped'),
('leather chairs','chairs','mapped'),
('lemon',NULL,'excluded'),
('leopard chair','leopard chairs','mapped'),
('letter decor','letter decors','mapped'),
('letterbox','letterboxes','mapped'),
('lifebuoy','lifebuoies','mapped'),
('light','lights','mapped'),
('light fixture','light fixtures','mapped'),
('light fixtures','light fixtures','mapped'),
('light strip','light strips','mapped'),
('light switch',NULL,'excluded'),
('light switches',NULL,'excluded'),
('light wood',NULL,'excluded'),
('light wood bench','benches','mapped'),
('light wood chair','chairs','mapped'),
('light wood chairs','chairs','mapped'),
('light wood dining chairs','dining chairs','mapped'),
('light wood legs','legs','mapped'),
('light wood seats','seats','mapped'),
('light wood stools','stools','mapped'),
('lightbox','lightboxes','mapped'),
('lighting','lighting','mapped'),
('lighting fixtures','lighting fixtures','mapped'),
('lights','lights','mapped'),
('lightswitch',NULL,'excluded'),
('locker','lockers','mapped'),
('lockers','lockers','mapped'),
('lotion bottle','lotion bottles','mapped'),
('luggage',NULL,'excluded'),
('macrame wall hanging','macrame wall hangings','mapped'),
('magazine','magazines','mapped'),
('magazines','magazines','mapped'),
('mannequin','mannequins','mapped'),
('mantelpiece','mantelpieces','mapped'),
('map','maps','mapped'),
('map wallpaper','map wallpapers','mapped'),
('mask','masks','mapped'),
('massage table','massage tables','mapped'),
('mat','mats','mapped'),
('media cabinet','tv units','mapped'),
('media console','tv units','mapped'),
('media unit','tv units','mapped'),
('mesh',NULL,'excluded'),
('mesh chair','mesh chairs','mapped'),
('metal chair','chairs','mapped'),
('metal chairs','chairs','mapped'),
('metal frame chairs','frame chairs','mapped'),
('metallic',NULL,'excluded'),
('metallic chair','chairs','mapped'),
('metallic chairs','chairs','mapped'),
('metallic frame','frames','mapped'),
('metallic legs','legs','mapped'),
('microphone','microphones','mapped'),
('microscope','microscopes','mapped'),
('microwave','microwaves','mapped'),
('mirror','mirrors','mapped'),
('mirror cabinet','mirror cabinets','mapped'),
('mirror doors','mirror doors','mapped'),
('mirror frame','mirrors','mapped'),
('mirror wall art','mirror wall arts','mapped'),
('mirrors','mirrors','mapped'),
('mobile','mobiles','mapped'),
('model sailboat','model sailboats','mapped'),
('model ship','model ships','mapped'),
('modern chair','modern chairs','mapped'),
('modern chairs','modern chairs','mapped'),
('modern dining chairs','modern dining chairs','mapped'),
('monitor','monitors','mapped'),
('monkey plush','monkey plushes','mapped'),
('monkey toys','monkey toys','mapped'),
('moon ornament','moon ornaments','mapped'),
('mop',NULL,'excluded'),
('moss art','moss arts','mapped'),
('mouse','mouses','mapped'),
('mug','mugs','mapped'),
('mugs','mugs','mapped'),
('mural','murals','mapped'),
('mushroom decoration','mushroom decorations','mapped'),
('name wall art','name wall arts','mapped'),
('napkin','napkins','mapped'),
('napkin rings','napkin rings','mapped'),
('napkins','napkins','mapped'),
('natural',NULL,'excluded'),
('natural wood chairs','chairs','mapped'),
('natural woven seats','natural woven seats','mapped'),
('neon light','neon lights','mapped'),
('neon sign','neon signs','mapped'),
('net','nets','mapped'),
('net canopy','net canopies','mapped'),
('netting','nettings','mapped'),
('newspaper','newspapers','mapped'),
('night lamp','night lamps','mapped'),
('nightstand','bedside tables','mapped'),
('nightstands','bedside tables','mapped'),
('notebook','notebooks','mapped'),
('notice board','notice boards','mapped'),
('noticeboard','noticeboards','mapped'),
('oars','oars','mapped'),
('office chair','office chairs','mapped'),
('oranges',NULL,'excluded'),
('ornament','ornaments','mapped'),
('ornaments','ornaments','mapped'),
('ottoman','ottomans','mapped'),
('ottomans','ottomans','mapped'),
('outdoor chairs','outdoor chairs','mapped'),
('outdoor furniture','outdoor furnitures','mapped'),
('outdoor table','outdoor tables','mapped'),
('outlet',NULL,'excluded'),
('oven','ovens','mapped'),
('oven hob','oven hobs','mapped'),
('oven unit','oven units','mapped'),
('paint','paints','mapped'),
('paint palette','paint palettes','mapped'),
('painting','artwork','mapped'),
('paintings','artwork','mapped'),
('pampas grass','pampas grass','mapped'),
('pan','pans','mapped'),
('panda chair','panda chairs','mapped'),
('panda plush','panda plushes','mapped'),
('partition','partitions','mapped'),
('pasta containers','pasta containers','mapped'),
('patio','patios','mapped'),
('patio door','patio doors','mapped'),
('patio furniture','patio furnitures','mapped'),
('patterned armchair','armchairs','mapped'),
('patterned chair','chairs','mapped'),
('patterned chairs','chairs','mapped'),
('patterned seats','seats','mapped'),
('patterned upholstery','upholsteries','mapped'),
('pedestal sink','bathroom basins','mapped'),
('peg holder','peg holders','mapped'),
('pegboard','pegboards','mapped'),
('pen holder','pen holders','mapped'),
('pencils','pencils','mapped'),
('pendant lamp','pendant lights','mapped'),
('pendant lamps','pendant lights','mapped'),
('pendant light','pendant lights','mapped'),
('pendant lights','pendant lights','mapped'),
('pepper mill','pepper mills','mapped'),
('perfume bottle','perfume bottles','mapped'),
('person',NULL,'excluded'),
('pet bed','pet beds','mapped'),
('pet food bowls','pet food bowls','mapped'),
('pet food containers','pet food containers','mapped'),
('phone','phones','mapped'),
('photo frame','picture frames','mapped'),
('photograph frame','picture frames','mapped'),
('photos','photos','mapped'),
('piano','pianos','mapped'),
('picnic bench','picnic benches','mapped'),
('picnic table','picnic tables','mapped'),
('picture','artwork','mapped'),
('picture frame','artwork','mapped'),
('picture frames','picture frames','mapped'),
('pictures','artwork','mapped'),
('pillars','pillars','mapped'),
('pillow','pillows','mapped'),
('pillows','pillows','mapped'),
('pinboard','pinboards','mapped'),
('pipe',NULL,'excluded'),
('pitcher','pitchers','mapped'),
('placemat','placemats','mapped'),
('placemats','placemats','mapped'),
('plaid armchair','plaid armchairs','mapped'),
('plant','plants','mapped'),
('plant basket','baskets','mapped'),
('plant hanger','plant hangers','mapped'),
('plant hangers','plant hangers','mapped'),
('plant holder','plant holders','mapped'),
('plant pot','plant pots','mapped'),
('plant pots','plant pots','mapped'),
('plant shelf','plant shelfs','mapped'),
('plant stand','plant stands','mapped'),
('planter','plant pots','mapped'),
('planters','plant pots','mapped'),
('plants','plants','mapped'),
('plate','plates','mapped'),
('plates','plates','mapped'),
('plates and bowls','plates and bowls','mapped'),
('play tent','play tents','mapped'),
('plug socket',NULL,'excluded'),
('plush','plushes','mapped'),
('plush toy','plush toys','mapped'),
('plush toys','plush toys','mapped'),
('popcorn bucket','popcorn buckets','mapped'),
('poster','posters','mapped'),
('pot','pots','mapped'),
('pots','pots','mapped'),
('pots and pans','pots and pans','mapped'),
('potted plant','plants','mapped'),
('potted plants','plants','mapped'),
('pouf','poufs','mapped'),
('pouffe','pouffes','mapped'),
('power outlet',NULL,'excluded'),
('power socket',NULL,'excluded'),
('printer','printers','mapped'),
('projector','projectors','mapped'),
('projector screen','projector screens','mapped'),
('promotional panel',NULL,'excluded'),
('propeller','propellers','mapped'),
('pump bottles','pump bottles','mapped'),
('quilt','quilts','mapped'),
('quilted chairs','quilted chairs','mapped'),
('rabbit headboard decoration','rabbit headboard decorations','mapped'),
('rack','racks','mapped'),
('radiator','radiators','mapped'),
('radiator cover','radiator covers','mapped'),
('radiators','radiators','mapped'),
('radio','radios','mapped'),
('rail','rails','mapped'),
('railing','railings','mapped'),
('railings','railings','mapped'),
('rainbow','rainbows','mapped'),
('rainbow decoration','rainbow decorations','mapped'),
('rainbow ornament','rainbow ornaments','mapped'),
('range hood','range hoods','mapped'),
('rattan chair','chairs','mapped'),
('receptacle','receptacles','mapped'),
('recessed lighting','recessed lightings','mapped'),
('recessed shelf','recessed shelfs','mapped'),
('record player','record players','mapped'),
('reed diffuser','reed diffusers','mapped'),
('reeds','reeds','mapped'),
('reeds diffuser','reed diffusers','mapped'),
('refrigerator','refrigerators','mapped'),
('remote','remotes','mapped'),
('remote control','remote controls','mapped'),
('ring light','ring lights','mapped'),
('robe',NULL,'excluded'),
('robes',NULL,'excluded'),
('rocking chair','rocking chairs','mapped'),
('rocking elephant','rocking elephants','mapped'),
('rocking elephant toy','rocking elephant toies','mapped'),
('rocking horse','rocking horses','mapped'),
('rocking whale toy','rocking whale toies','mapped'),
('roller blind','roller blinds','mapped'),
('rolling pin','rolling pins','mapped'),
('roman blind','roman blinds','mapped'),
('room divider','room dividers','mapped'),
('rooster ornament','rooster ornaments','mapped'),
('round mirror','mirrors','mapped'),
('round rug','rugs','mapped'),
('round table','round tables','mapped'),
('round wall mirror','mirrors','mapped'),
('rubber ducks','rubber ducks','mapped'),
('rug','rugs','mapped'),
('rug rack','rug racks','mapped'),
('rugby ball','rugby balls','mapped'),
('rugs','rugs','mapped'),
('sailboat','sailboats','mapped'),
('salt and pepper shakers','salt and pepper shakers','mapped'),
('salt shaker','salt shakers','mapped'),
('saucer','saucers','mapped'),
('scale','scales','mapped'),
('scarf',NULL,'excluded'),
('scarves',NULL,'excluded'),
('sconces','wall lights','mapped'),
('scooter','scooters','mapped'),
('scoreboard','scoreboards','mapped'),
('screen','screens','mapped'),
('sculpture','sculptures','mapped'),
('sculptures','sculptures','mapped'),
('seahorse ornament','seahorse ornaments','mapped'),
('seashell','seashells','mapped'),
('seashell decor','seashell decors','mapped'),
('seating',NULL,'excluded'),
('sewing machine','sewing machines','mapped'),
('shaker','shakers','mapped'),
('shelf','shelving','mapped'),
('shelf unit','shelving','mapped'),
('shell','shells','mapped'),
('shelves','shelving','mapped'),
('shelving','shelving','mapped'),
('shelving unit','shelving','mapped'),
('ship model','ship models','mapped'),
('shirt',NULL,'excluded'),
('shoe',NULL,'excluded'),
('shoe rack','shoe racks','mapped'),
('shoes',NULL,'excluded'),
('shopping bag',NULL,'excluded'),
('shopping bags',NULL,'excluded'),
('shower','showers','mapped'),
('shower arm','shower arms','mapped'),
('shower caddy','shower caddies','mapped'),
('shower controls','shower controls','mapped'),
('shower curtain','shower curtains','mapped'),
('shower curtain rod','shower curtain rods','mapped'),
('shower door','shower doors','mapped'),
('shower door handle','shower door handles','mapped'),
('shower enclosure','shower enclosures','mapped'),
('shower fixture','shower fixtures','mapped'),
('shower glass','shower glass','mapped'),
('shower head','shower heads','mapped'),
('shower hose','shower hoses','mapped'),
('shower rack','shower racks','mapped'),
('shower rail','shower rails','mapped'),
('shower screen','shower screens','mapped'),
('shower tray','shower trays','mapped'),
('showerhead','showerheads','mapped'),
('shrub','shrubs','mapped'),
('shutters','shutters','mapped'),
('side lamp','side lamps','mapped'),
('side table','side tables','mapped'),
('side table lamp','side table lamps','mapped'),
('side tables','side tables','mapped'),
('sideboard','sideboards','mapped'),
('sign','signs','mapped'),
('signage','signages','mapped'),
('signs','signs','mapped'),
('sill','sills','mapped'),
('sink','sinks','mapped'),
('sink cabinet','vanity units','mapped'),
('sink pedestal','bathroom basins','mapped'),
('sink stand','sink stands','mapped'),
('sink unit','vanity units','mapped'),
('sink vanity','vanity units','mapped'),
('sinks','sinks','mapped'),
('skateboard','skateboards','mapped'),
('skateboards','skateboards','mapped'),
('skirting board','skirting boards','mapped'),
('skull','skulls','mapped'),
('skylight','skylights','mapped'),
('slide','slides','mapped'),
('sliding door','sliding doors','mapped'),
('sliding doors','sliding doors','mapped'),
('sliding glass door','sliding glass doors','mapped'),
('sliding wardrobe','sliding wardrobes','mapped'),
('slippers',NULL,'excluded'),
('slotted spoon','slotted spoons','mapped'),
('small mirror','mirrors','mapped'),
('small sofa','small sofas','mapped'),
('smoke detector',NULL,'excluded'),
('snail cushion','snail cushions','mapped'),
('soap',NULL,'excluded'),
('soap bottles','soap bottles','mapped'),
('soap dish','soap dishes','mapped'),
('soap dispenser','soap dispensers','mapped'),
('soap dispensers','soap dispensers','mapped'),
('soccer ball','soccer balls','mapped'),
('soccer ball pillow','soccer ball pillows','mapped'),
('soccer balls','soccer balls','mapped'),
('socket',NULL,'excluded'),
('sofa','sofas','mapped'),
('sofa chairs','sofas','mapped'),
('soft toy','soft toies','mapped'),
('spatula','spatulas','mapped'),
('speaker','speakers','mapped'),
('spice bottles','spice bottles','mapped'),
('spice jars','spice jars','mapped'),
('spices','spices','mapped'),
('spindle chair','spindle chairs','mapped'),
('splashback','splashbacks','mapped'),
('sponge',NULL,'excluded'),
('spoon','spoons','mapped'),
('spoons','spoons','mapped'),
('sports memorabilia','sports memorabilias','mapped'),
('spotlight','spotlights','mapped'),
('spotlights','spotlights','mapped'),
('spray bottle','spray bottles','mapped'),
('spray bottles','spray bottles','mapped'),
('stair rail','stair rails','mapped'),
('staircase','staircases','mapped'),
('staircase balustrade','staircase balustrades','mapped'),
('stairs','stairs','mapped'),
('stairs railing','stairs railings','mapped'),
('stand','stands','mapped'),
('star','stars','mapped'),
('star decoration','star decorations','mapped'),
('star decorations','star decorations','mapped'),
('star ornament','star ornaments','mapped'),
('star wall decor','star wall decors','mapped'),
('star wall hangings','star wall hangings','mapped'),
('starfish ornament','starfish ornaments','mapped'),
('stars','stars','mapped'),
('statue','ornaments','mapped'),
('statues','ornaments','mapped'),
('stool','stools','mapped'),
('stools','stools','mapped'),
('storage',NULL,'excluded'),
('storage bag','storage bags','mapped'),
('storage basket','baskets','mapped'),
('storage baskets','baskets','mapped'),
('storage bench','storage benches','mapped'),
('storage bin','storage bins','mapped'),
('storage box','storage boxes','mapped'),
('storage boxes','storage boxes','mapped'),
('storage cabinet','storage cabinets','mapped'),
('storage canisters','storage canisters','mapped'),
('storage cart','storage carts','mapped'),
('storage chest','storage chests','mapped'),
('storage container','storage containers','mapped'),
('storage jar','storage jars','mapped'),
('storage jars','storage jars','mapped'),
('storage rack','storage racks','mapped'),
('storage shelf','shelving','mapped'),
('storage unit','storage units','mapped'),
('stove','stoves','mapped'),
('stovetop','stovetops','mapped'),
('string light fixture','string light fixtures','mapped'),
('string lights','string lights','mapped'),
('striped armchair','armchairs','mapped'),
('striped chair','chairs','mapped'),
('striped chairs','chairs','mapped'),
('striped cushions','cushions','mapped'),
('striped towel','towels','mapped'),
('stroller','strollers','mapped'),
('studded chair','studded chairs','mapped'),
('studded chairs','studded chairs','mapped'),
('stuffed animal','stuffed animals','mapped'),
('stuffed animals','stuffed animals','mapped'),
('stuffed bear','stuffed bears','mapped'),
('stuffed giraffe','stuffed giraffes','mapped'),
('stuffed octopus','stuffed octopus','mapped'),
('stuffed rabbit','stuffed rabbits','mapped'),
('stuffed rabbits','stuffed rabbits','mapped'),
('stuffed toy','stuffed toies','mapped'),
('stuffed toys','stuffed toies','mapped'),
('suitcase',NULL,'excluded'),
('sun','suns','mapped'),
('sun decoration','sun decorations','mapped'),
('sunflowers','sunflowers','mapped'),
('surfboard','surfboards','mapped'),
('swing chair','swing chairs','mapped'),
('switch',NULL,'excluded'),
('swivel chair','swivel chairs','mapped'),
('t-shirt',NULL,'excluded'),
('table','tables','mapped'),
('table lamp','table lamps','mapped'),
('table lamps','table lamps','mapped'),
('table runner','table runners','mapped'),
('tablecloth','tablecloths','mapped'),
('tables','tables','mapped'),
('tablet','tablets','mapped'),
('tableware','tableware','mapped'),
('tajine','tajines','mapped'),
('tan',NULL,'excluded'),
('tap','taps','mapped'),
('tapestry','tapestries','mapped'),
('taps','taps','mapped'),
('teapot','teapots','mapped'),
('teapot and mug','teapot and mugs','mapped'),
('teapot set','teapot sets','mapped'),
('teddy bear','teddy bears','mapped'),
('teddy bears','teddy bears','mapped'),
('teepee','teepees','mapped'),
('telephone','telephones','mapped'),
('telescope','telescopes','mapped'),
('television','televisions','mapped'),
('television stand','tv units','mapped'),
('tennis racket','tennis rackets','mapped'),
('tent','tents','mapped'),
('tents','tents','mapped'),
('tepee','tepees','mapped'),
('text box',NULL,'excluded'),
('textured chairs','textured chairs','mapped'),
('thermostat',NULL,'excluded'),
('throw','throws','mapped'),
('throw blanket','throws','mapped'),
('tiger','tigers','mapped'),
('tiki statue','tiki statues','mapped'),
('tiled floor','tiled floors','mapped'),
('tiled wall','tiled walls','mapped'),
('tiles','tiles','mapped'),
('tissue box','tissue boxes','mapped'),
('tissue holder','tissue holders','mapped'),
('toaster','toasters','mapped'),
('toilet','toilets','mapped'),
('toilet brush','toilet brushes','mapped'),
('toilet brush holder','toilet brush holders','mapped'),
('toilet cistern','toilet cisterns','mapped'),
('toilet flush plate','toilet flush plates','mapped'),
('toilet paper',NULL,'excluded'),
('toilet paper holder','toilet paper holders','mapped'),
('toilet roll holder','toilet roll holders','mapped'),
('toiletries',NULL,'excluded'),
('tomatoes',NULL,'excluded'),
('tool','tools','mapped'),
('tool wall','tool walls','mapped'),
('toothbrush holder','toothbrush holders','mapped'),
('tote bag',NULL,'excluded'),
('towel','towels','mapped'),
('towel bag','towel bags','mapped'),
('towel bar','towel bars','mapped'),
('towel basket','baskets','mapped'),
('towel case','towel cases','mapped'),
('towel dispenser','towel dispensers','mapped'),
('towel holder','towel holders','mapped'),
('towel ladder','towel ladders','mapped'),
('towel on floor','towels','mapped'),
('towel on toilet','towels','mapped'),
('towel on warmer','towels','mapped'),
('towel rack','towel racks','mapped'),
('towel radiator','towel radiators','mapped'),
('towel rail','towel rails','mapped'),
('towel ring','towel rings','mapped'),
('towel roll','towels','mapped'),
('towel shelf','towel shelfs','mapped'),
('towel stack','towels','mapped'),
('towel stand','towel stands','mapped'),
('towel tray','towel trays','mapped'),
('towel warmer','towel warmers','mapped'),
('towels','towels','mapped'),
('toy','toies','mapped'),
('toy basket','baskets','mapped'),
('toy bed','toy beds','mapped'),
('toy box','toy boxes','mapped'),
('toy bus','toy bus','mapped'),
('toy car','toy cars','mapped'),
('toy cars','toy cars','mapped'),
('toy cart','toy carts','mapped'),
('toy castle','toy castles','mapped'),
('toy elephant','toy elephants','mapped'),
('toy excavator','toy excavators','mapped'),
('toy house','toy houses','mapped'),
('toy kitchen','toy kitchens','mapped'),
('toy shelf','toy shelfs','mapped'),
('toy stand','toy stands','mapped'),
('toy storage','toy storages','mapped'),
('toy table','toy tables','mapped'),
('toy tea set','toy tea sets','mapped'),
('toy tractor','toy tractors','mapped'),
('toy train','toy trains','mapped'),
('toy train table','toy train tables','mapped'),
('toy truck','toy trucks','mapped'),
('toys','toies','mapped'),
('toys box','toys boxes','mapped'),
('track lighting','track lightings','mapped'),
('trash bin','trash bins','mapped'),
('trash can','trash cans','mapped'),
('tray','trays','mapped'),
('tray table','tray tables','mapped'),
('trays','trays','mapped'),
('treadmill','treadmills','mapped'),
('treats container','treats containers','mapped'),
('tree decoration','tree decorations','mapped'),
('trim','trims','mapped'),
('trolley','trolleys','mapped'),
('trophy','trophies','mapped'),
('trunk','trunks','mapped'),
('trunks','trunks','mapped'),
('tub','bath tubs','mapped'),
('tub tray','bath trays','mapped'),
('tufted armchair','armchairs','mapped'),
('tufted chair','chairs','mapped'),
('tufted chairs','chairs','mapped'),
('tumble dryer','tumble dryers','mapped'),
('turntables','turntables','mapped'),
('tv','televisions','mapped'),
('tv cabinet','tv units','mapped'),
('tv shelf','tv shelfs','mapped'),
('tv stand','tv units','mapped'),
('tv unit','tv units','mapped'),
('tv wall unit','tv units','mapped'),
('typewriter','typewriters','mapped'),
('umbrella','umbrellas','mapped'),
('umbrella stand','umbrella stands','mapped'),
('upholstered bench','benches','mapped'),
('upholstered chair','chairs','mapped'),
('upholstered chairs','chairs','mapped'),
('urn','urns','mapped'),
('utensil','utensils','mapped'),
('utensil holder','utensil holders','mapped'),
('utensils','utensils','mapped'),
('valance','valances','mapped'),
('valve',NULL,'excluded'),
('vanity','vanity units','mapped'),
('vanity cabinet','vanity units','mapped'),
('vanity unit','vanity units','mapped'),
('vase','vases','mapped'),
('vases','vases','mapped'),
('vegetable',NULL,'excluded'),
('velvet armchair','armchairs','mapped'),
('velvet chair','chairs','mapped'),
('velvet chairs','chairs','mapped'),
('vent',NULL,'excluded'),
('vest',NULL,'excluded'),
('vine','vines','mapped'),
('wall',NULL,'excluded'),
('wall art','wall arts','mapped'),
('wall cabinet','wall cabinets','mapped'),
('wall clock','wall clocks','mapped'),
('wall decal','wall decals','mapped'),
('wall decals','wall decals','mapped'),
('wall decor','wall decors','mapped'),
('wall decoration','wall decorations','mapped'),
('wall decorations','wall decorations','mapped'),
('wall grid','wall grids','mapped'),
('wall hanging','wall hangings','mapped'),
('wall heater','wall heaters','mapped'),
('wall hooks','wall hooks','mapped'),
('wall lamp','wall lights','mapped'),
('wall lamps','wall lights','mapped'),
('wall light','wall lights','mapped'),
('wall mirror','mirrors','mapped'),
('wall mirrors','mirrors','mapped'),
('wall mural','wall murals','mapped'),
('wall niche','wall niches','mapped'),
('wall ornament','wall ornaments','mapped'),
('wall outlet',NULL,'excluded'),
('wall outlets',NULL,'excluded'),
('wall panel','wall panelling','mapped'),
('wall paneling','wall panelling','mapped'),
('wall planter','wall planters','mapped'),
('wall plates','wall plates','mapped'),
('wall rack','wall racks','mapped'),
('wall sconce','wall lights','mapped'),
('wall sconces','wall lights','mapped'),
('wall shelf','shelving','mapped'),
('wall shelves','shelving','mapped'),
('wall sign','wall signs','mapped'),
('wall socket',NULL,'excluded'),
('wall sockets',NULL,'excluded'),
('wall switch',NULL,'excluded'),
('wall tile','wall tiles','mapped'),
('wall tiles','wall tiles','mapped'),
('wall unit','wall units','mapped'),
('wall-mounted basket','wall-mounted baskets','mapped'),
('wall-mounted baskets','wall-mounted baskets','mapped'),
('wall-mounted board','wall-mounted boards','mapped'),
('wall-mounted boiler',NULL,'excluded'),
('wall-mounted box','wall-mounted boxes','mapped'),
('wall-mounted cabinet','wall-mounted cabinets','mapped'),
('wall-mounted circular device','wall-mounted circular devices','mapped'),
('wall-mounted clock','wall-mounted clocks','mapped'),
('wall-mounted controls','wall-mounted controls','mapped'),
('wall-mounted device','wall-mounted devices','mapped'),
('wall-mounted heater','wall-mounted heaters','mapped'),
('wall-mounted holder','wall-mounted holders','mapped'),
('wall-mounted hooks','wall-mounted hooks','mapped'),
('wall-mounted lamp','wall lights','mapped'),
('wall-mounted lantern','wall-mounted lanterns','mapped'),
('wall-mounted light','wall lights','mapped'),
('wall-mounted phone','wall-mounted phones','mapped'),
('wall-mounted plant holder','wall-mounted plant holders','mapped'),
('wall-mounted plant holders','wall-mounted plant holders','mapped'),
('wall-mounted planter grid','wall-mounted planter grids','mapped'),
('wall-mounted planters','wall-mounted planters','mapped'),
('wall-mounted rack','wall-mounted racks','mapped'),
('wall-mounted radiator','wall-mounted radiators','mapped'),
('wall-mounted shelf','shelving','mapped'),
('wall-mounted soap dispenser','wall-mounted soap dispensers','mapped'),
('wall-mounted switch','wall-mounted switches','mapped'),
('wall-mounted toilet','wall-mounted toilets','mapped'),
('wall-mounted toilet cistern','wall-mounted toilet cisterns','mapped'),
('wall-mounted toilet flush','wall-mounted toilet flushes','mapped'),
('wall-mounted toilet flush plate','wall-mounted toilet flush plates','mapped'),
('wall-mounted toilet paper holder','wall-mounted toilet paper holders','mapped'),
('wall-mounted tv','televisions','mapped'),
('wall-mounted unit','wall-mounted units','mapped'),
('wallpaper','wallpaper','mapped'),
('wallpaper mural','wallpaper murals','mapped'),
('walls',NULL,'excluded'),
('wardrobe','wardrobes','mapped'),
('wardrobes','wardrobes','mapped'),
('washbasin','bathroom basins','mapped'),
('washing machine','washing machines','mapped'),
('washing machines','washing machines','mapped'),
('waste basket','waste baskets','mapped'),
('waste bin','waste bins','mapped'),
('water bottle','water bottles','mapped'),
('water heater',NULL,'excluded'),
('water jug','water jugs','mapped'),
('water pitcher','water pitchers','mapped'),
('watering can','watering cans','mapped'),
('whale ornament','whale ornaments','mapped'),
('whisk','whisks','mapped'),
('whiteboard','whiteboards','mapped'),
('wicker bar stools','bar stools','mapped'),
('wicker basket','baskets','mapped'),
('wicker baskets','baskets','mapped'),
('wicker chair','chairs','mapped'),
('wicker chairs','chairs','mapped'),
('wicker chest','chests','mapped'),
('wicker dining chairs','dining chairs','mapped'),
('wicker storage',NULL,'excluded'),
('wicker storage container','storage containers','mapped'),
('wicker tray','trays','mapped'),
('window',NULL,'excluded'),
('window blind','blinds','mapped'),
('window blinds','blinds','mapped'),
('window decor','window decors','mapped'),
('window decoration','window decorations','mapped'),
('window frame',NULL,'excluded'),
('window frames','window frames','mapped'),
('window handle','window handles','mapped'),
('window ornament','window ornaments','mapped'),
('window seat','window seats','mapped'),
('window sign','window signs','mapped'),
('window sill','window sills','mapped'),
('window sill decor','window sill decors','mapped'),
('window sill decoration','window sill decorations','mapped'),
('window sill ornament','window sill ornaments','mapped'),
('window sill ornaments','window sill ornaments','mapped'),
('window sills','window sills','mapped'),
('window treatment','window treatments','mapped'),
('window treatments','window treatments','mapped'),
('window valance','window valances','mapped'),
('windows',NULL,'excluded'),
('windowsill','windowsills','mapped'),
('wine bottle','wine bottles','mapped'),
('wine bottles','wine bottles','mapped'),
('wine cabinet','wine cabinets','mapped'),
('wine cooler','wine coolers','mapped'),
('wine fridge','wine fridges','mapped'),
('wine glass','wine glass','mapped'),
('wine glasses','wine glasses','mapped'),
('wine rack','wine racks','mapped'),
('wire basket','baskets','mapped'),
('wire chair','chairs','mapped'),
('wood',NULL,'excluded'),
('wood and metal bar stools','and metal bar stools','mapped'),
('wood chair','chairs','mapped'),
('wood chairs','chairs','mapped'),
('wood panel','panels','mapped'),
('wood stools','stools','mapped'),
('wooden accent wall','accent walls','mapped'),
('wooden armchair','armchairs','mapped'),
('wooden armchairs','armchairs','mapped'),
('wooden bar stools','bar stools','mapped'),
('wooden barstools','bar stools','mapped'),
('wooden basin','bathroom basins','mapped'),
('wooden bath mat','bath mats','mapped'),
('wooden bath tray','bath trays','mapped'),
('wooden bench','benches','mapped'),
('wooden blocks','blocks','mapped'),
('wooden boat bed','boat beds','mapped'),
('wooden bowl','bowls','mapped'),
('wooden box','boxes','mapped'),
('wooden brush','brushes','mapped'),
('wooden cabinet','cabinets','mapped'),
('wooden castle','castles','mapped'),
('wooden chair','chairs','mapped'),
('wooden chairs','chairs','mapped'),
('wooden crate','crates','mapped'),
('wooden cutting board','chopping boards','mapped'),
('wooden cutting boards','chopping boards','mapped'),
('wooden dining chairs','dining chairs','mapped'),
('wooden door','doors','mapped'),
('wooden door panel','door panels','mapped'),
('wooden floor',NULL,'excluded'),
('wooden ladder shelf','ladder shelfs','mapped'),
('wooden legs','legs','mapped'),
('wooden panel','panels','mapped'),
('wooden partition','partitions','mapped'),
('wooden rabbit','rabbits','mapped'),
('wooden shelf','shelving','mapped'),
('wooden side table','side tables','mapped'),
('wooden spoons','spoons','mapped'),
('wooden stool','stools','mapped'),
('wooden stools','stools','mapped'),
('wooden structure','structures','mapped'),
('wooden table','tables','mapped'),
('wooden tray','trays','mapped'),
('wooden utensil holder','utensil holders','mapped'),
('wooden utensils','utensils','mapped'),
('workbench','workbenches','mapped'),
('worktop','worktops','mapped'),
('world map','world maps','mapped'),
('world map rug','world map rugs','mapped'),
('woven',NULL,'excluded'),
('woven bar stools','bar stools','mapped'),
('woven basket','baskets','mapped'),
('woven baskets','baskets','mapped'),
('woven chair','chairs','mapped'),
('woven chairs','chairs','mapped'),
('woven seat','seats','mapped'),
('wreath','wreaths','mapped'),
('yoga mat','yoga mats','mapped'),
('zebra head ornament','zebra head ornaments','mapped');
-- Small indexed mapping join; no JSON extraction on directory/filter requests.
create view showhome_web.image_furnishing_categories as
 select distinct f.image_key,f.builder_slug,f.image_id,m.category_name as name
 from showhome_web.image_furnishings f join showhome_web.furnishing_category_mappings m on m.source_name=f.name
 where m.category_name is not null;
create function showhome_web.queue_unmapped_furnishing() returns trigger language plpgsql as $$
begin
 insert into showhome_web.furnishing_category_mappings(source_name) values(NEW.name) on conflict do nothing;
 return NEW;
end $$;
create trigger queue_unmapped_furnishing after insert on showhome_web.image_furnishings
 for each row execute function showhome_web.queue_unmapped_furnishing();
insert into showhome_web.furnishing_category_mappings(source_name)
 select distinct name from showhome_web.image_furnishings on conflict do nothing;
revoke all on showhome_web.furnishing_category_mappings,showhome_web.image_furnishing_categories from anon,authenticated;
revoke all on function showhome_web.queue_unmapped_furnishing() from public;
-- Summaries and caches built with raw labels cannot be served as mapped categories.
delete from showhome_web.query_cache;
delete from showhome_web.gallery_publication_summaries;
analyze showhome_web.furnishing_category_mappings;
