-- Refine public groups without altering any original image classification.
-- Explicit aliases, not fuzzy runtime matching. Null categories are excluded.
insert into showhome_web.furnishing_category_mappings(source_name,category_name,decision) values
('accent chair','armchairs','mapped'),
('accent wall','wall panelling','mapped'),
('accessories',NULL,'excluded'),
('air conditioner',NULL,'excluded'),
('air conditioning unit',NULL,'excluded'),
('air freshener',NULL,'excluded'),
('airplane decals','wall decals','mapped'),
('airplane models','ornaments','mapped'),
('alarm clock','alarm clocks','mapped'),
('amplifier',NULL,'excluded'),
('appliance',NULL,'excluded'),
('appliances',NULL,'excluded'),
('apron',NULL,'excluded'),
('aprons',NULL,'excluded'),
('arched mirror','mirrors','mapped'),
('arched wall panel','wall panelling','mapped'),
('area rug','rugs','mapped'),
('armchair','armchairs','mapped'),
('armchairs','armchairs','mapped'),
('arrow',NULL,'excluded'),
('art','artwork','mapped'),
('art easel',NULL,'excluded'),
('artichokes',NULL,'excluded'),
('artificial plants','plants','mapped'),
('artwork','artwork','mapped'),
('artwork frame','picture frames','mapped'),
('artworks','artwork','mapped'),
('asparagus',NULL,'excluded'),
('backpack',NULL,'excluded'),
('backrest',NULL,'excluded'),
('backsplash','splashbacks','mapped'),
('bag',NULL,'excluded'),
('bags',NULL,'excluded'),
('balance bike',NULL,'excluded'),
('balcony',NULL,'excluded'),
('balcony door',NULL,'excluded'),
('balcony doors',NULL,'excluded'),
('balcony railing','stair railings','mapped'),
('ball',NULL,'excluded'),
('ball pit',NULL,'excluded'),
('balustrade','stair railings','mapped'),
('bamboo divider','room dividers','mapped'),
('bamboo screen','room dividers','mapped'),
('banister','stair railings','mapped'),
('banner',NULL,'excluded'),
('banners',NULL,'excluded'),
('bar','breakfast bars','mapped'),
('bar cart','bar carts','mapped'),
('bar counter','breakfast bars','mapped'),
('bar stool','bar stools','mapped'),
('bar stools','bar stools','mapped'),
('barrel',NULL,'excluded'),
('barstool','bar stools','mapped'),
('barstools','bar stools','mapped'),
('base cabinet','kitchen cabinets','mapped'),
('baseboard','skirting boards','mapped'),
('baseboards','skirting boards','mapped'),
('basin','bathroom basins','mapped'),
('basin unit','vanity units','mapped'),
('basket','baskets','mapped'),
('basketball hoop',NULL,'excluded'),
('baskets','baskets','mapped'),
('bath','baths','mapped'),
('bath accessories',NULL,'excluded'),
('bath basket','baskets','mapped'),
('bath brush',NULL,'excluded'),
('bath caddy','bath trays','mapped'),
('bath candle','candles','mapped'),
('bath items',NULL,'excluded'),
('bath lotion',NULL,'excluded'),
('bath mat','bath mats','mapped'),
('bath oil',NULL,'excluded'),
('bath products',NULL,'excluded'),
('bath reed diffuser','reed diffusers','mapped'),
('bath salts',NULL,'excluded'),
('bath scrubber',NULL,'excluded'),
('bath soap',NULL,'excluded'),
('bath sponge',NULL,'excluded'),
('bath towel','towels','mapped'),
('bath towels','towels','mapped'),
('bath toys',NULL,'excluded'),
('bath tray','bath trays','mapped'),
('bathrobe',NULL,'excluded'),
('bathroom',NULL,'excluded'),
('bathroom accessories',NULL,'excluded'),
('bathroom bottles',NULL,'excluded'),
('bathroom cabinet','bathroom cabinets','mapped'),
('bathroom cabinet frame','bathroom cabinets','mapped'),
('bathroom ceiling',NULL,'excluded'),
('bathroom door',NULL,'excluded'),
('bathroom door frame',NULL,'excluded'),
('bathroom fixtures',NULL,'excluded'),
('bathroom floor',NULL,'excluded'),
('bathroom mat','bath mats','mapped'),
('bathroom mirror','mirrors','mapped'),
('bathroom mirror frame','mirrors','mapped'),
('bathroom products',NULL,'excluded'),
('bathroom rack','shower caddies','mapped'),
('bathroom shelf','shelving','mapped'),
('bathroom shelf frame','shelving','mapped'),
('bathroom shower','showers','mapped'),
('bathroom sink','bathroom basins','mapped'),
('bathroom sink frame','bathroom basins','mapped'),
('bathroom tiles','wall tiles','mapped'),
('bathroom toilet','toilets','mapped'),
('bathroom toilet frame','toilets','mapped'),
('bathroom towel','towels','mapped'),
('bathroom towel rack','towel rails','mapped'),
('bathroom towels','towels','mapped'),
('bathroom wall',NULL,'excluded'),
('bathtub','baths','mapped'),
('bean bag','bean bags','mapped'),
('bean bag chair','bean bags','mapped'),
('beanbag','bean bags','mapped'),
('beanbag chair','bean bags','mapped'),
('bear rug','rugs','mapped'),
('bed','beds','mapped'),
('bed base',NULL,'excluded'),
('bed canopy','bed canopies','mapped'),
('bed cushions','cushions','mapped'),
('bed frame','bed frames','mapped'),
('bed ottoman','ottomans','mapped'),
('bedding','bedding','mapped'),
('beds','beds','mapped'),
('bedside cabinet','bedside tables','mapped'),
('bedside chair','chairs','mapped'),
('bedside lamp','table lamps','mapped'),
('bedside shelf','bedside tables','mapped'),
('bedside table','bedside tables','mapped'),
('bedside tables','bedside tables','mapped'),
('bedspread','bedding','mapped'),
('bench','benches','mapped'),
('bench chair','benches','mapped'),
('bench cover',NULL,'excluded'),
('bench cushion','cushions','mapped'),
('benches','benches','mapped'),
('bi-fold doors','bifold doors','mapped'),
('bicycle',NULL,'excluded'),
('bicycle rack',NULL,'excluded'),
('bifold door','bifold doors','mapped'),
('bin','bins','mapped'),
('binder',NULL,'excluded'),
('bird figurine','ornaments','mapped'),
('blackboard','noticeboards','mapped'),
('blanket','blankets','mapped'),
('blankets','blankets','mapped'),
('blind','blinds','mapped'),
('blinds','blinds','mapped'),
('board',NULL,'excluded'),
('boat','ornaments','mapped'),
('boiler',NULL,'excluded'),
('book','books','mapped'),
('bookcase','bookcases','mapped'),
('books','books','mapped'),
('bookshelf','bookcases','mapped'),
('bookshelf contents',NULL,'excluded'),
('bookshelves','bookcases','mapped'),
('boot',NULL,'excluded'),
('boots',NULL,'excluded'),
('bottle',NULL,'excluded'),
('bottles',NULL,'excluded'),
('bouclé armchair','armchairs','mapped'),
('boucle chair','armchairs','mapped'),
('bouclé chairs','chairs','mapped'),
('bowl','bowls','mapped'),
('bowls','bowls','mapped'),
('box','storage boxes','mapped'),
('boxes','storage boxes','mapped'),
('bread',NULL,'excluded'),
('bread bin','bread bins','mapped'),
('breadboard','chopping boards','mapped'),
('breakfast bar','breakfast bars','mapped'),
('broad wall panel','wall panelling','mapped'),
('broadboards',NULL,'excluded'),
('broadwall',NULL,'excluded'),
('broom',NULL,'excluded'),
('brush',NULL,'excluded'),
('brushes',NULL,'excluded'),
('bucket',NULL,'excluded'),
('built-in niche','wall niches','mapped'),
('built-in shelving','shelving','mapped'),
('bunk bed','bunk beds','mapped'),
('bunting','garlands','mapped'),
('cabinet','cabinets','mapped'),
('cabinet handles','cabinet handles','mapped'),
('cabinet knobs','cabinet handles','mapped'),
('cabinetry','kitchen cabinets','mapped'),
('cabinets','cabinets','mapped'),
('cactus','plants','mapped'),
('cactus decoration','ornaments','mapped'),
('caddy',NULL,'excluded'),
('calendar',NULL,'excluded'),
('camera',NULL,'excluded'),
('candelabra','candle holders','mapped'),
('candelabrum','candle holders','mapped'),
('candle','candles','mapped'),
('candle holder','candle holders','mapped'),
('candle holders','candle holders','mapped'),
('candle lantern','lanterns','mapped'),
('candles','candles','mapped'),
('candlestick','candle holders','mapped'),
('candlesticks','candle holders','mapped'),
('cane chair','chairs','mapped'),
('canister','storage jars','mapped'),
('canisters','storage jars','mapped'),
('canopy',NULL,'excluded'),
('cap',NULL,'excluded'),
('caps',NULL,'excluded'),
('carafe','jugs','mapped'),
('carpet','carpets','mapped'),
('carrots',NULL,'excluded'),
('cart','bar carts','mapped'),
('cat bed','pet beds','mapped'),
('cat tree','cat trees','mapped'),
('ceiling',NULL,'excluded'),
('ceiling decor',NULL,'excluded'),
('ceiling decoration',NULL,'excluded'),
('ceiling decorations',NULL,'excluded'),
('ceiling fan','ceiling fans','mapped'),
('ceiling fixture','ceiling lights','mapped'),
('ceiling lamp','ceiling lights','mapped'),
('ceiling light','ceiling lights','mapped'),
('ceiling light fixture','ceiling lights','mapped'),
('ceiling lights','ceiling lights','mapped'),
('ceiling molding',NULL,'excluded'),
('ceiling mural','wall murals','mapped'),
('cello',NULL,'excluded'),
('ceramic bowl','bowls','mapped'),
('ceramic bowls','bowls','mapped'),
('ceramic ornaments','ornaments','mapped'),
('ceramicware','tableware','mapped'),
('chair','chairs','mapped'),
('chairs','chairs','mapped'),
('chaise longue','chaise longues','mapped'),
('chaise lounge','chaise longues','mapped'),
('chalkboard','noticeboards','mapped'),
('chalkboard wall hanging','wall decorations','mapped'),
('champagne bottle',NULL,'excluded'),
('champagne bucket','ice buckets','mapped'),
('chandelier','chandeliers','mapped'),
('chandeliers','chandeliers','mapped'),
('changing table','changing tables','mapped'),
('chess set',NULL,'excluded'),
('chest','storage chests','mapped'),
('chest of drawers','chest of drawers','mapped'),
('chopping board','chopping boards','mapped'),
('chopping boards','chopping boards','mapped'),
('circular armchair','armchairs','mapped'),
('circular coffee table','coffee tables','mapped'),
('circular ottoman','ottomans','mapped'),
('circular rug','rugs','mapped'),
('circular sofa','sofas','mapped'),
('circular table','tables','mapped'),
('circular wooden board','chopping boards','mapped'),
('clear chair','chairs','mapped'),
('clock','clocks','mapped'),
('clocks','clocks','mapped'),
('closet','wardrobes','mapped'),
('closet door',NULL,'excluded'),
('closet drawer',NULL,'excluded'),
('closet rack',NULL,'excluded'),
('closet rod',NULL,'excluded'),
('closet shelf',NULL,'excluded'),
('closet shelves',NULL,'excluded'),
('cloth bag',NULL,'excluded'),
('clothes',NULL,'excluded'),
('clothes rack','clothes rails','mapped'),
('clothes rail','clothes rails','mapped'),
('clothing',NULL,'excluded'),
('clothing hanger',NULL,'excluded'),
('clothing rack','clothes rails','mapped'),
('clothing rail','clothes rails','mapped'),
('cloud decoration','ornaments','mapped'),
('cloud light','ceiling lights','mapped'),
('cloud shelves','shelving','mapped'),
('coat',NULL,'excluded'),
('coat hook','hooks','mapped'),
('coat hooks','hooks','mapped'),
('coat rack','coat racks','mapped'),
('coatrack','coat racks','mapped'),
('coffee cup','mugs','mapped'),
('coffee machine','coffee machines','mapped'),
('coffee maker','coffee machines','mapped'),
('coffee menu sign','wall decorations','mapped'),
('coffee mug','mugs','mapped'),
('coffee mugs','mugs','mapped'),
('coffee pot','teapots','mapped'),
('coffee table','coffee tables','mapped'),
('coffee tables','coffee tables','mapped'),
('colander','kitchen utensils','mapped'),
('compass',NULL,'excluded'),
('computer',NULL,'excluded'),
('computer monitor',NULL,'excluded'),
('cones',NULL,'excluded'),
('console','console tables','mapped'),
('console table','console tables','mapped'),
('container','storage containers','mapped'),
('containers','storage containers','mapped'),
('controller',NULL,'excluded'),
('controller decor','ornaments','mapped'),
('cookbook','books','mapped'),
('cooker hood','cooker hoods','mapped'),
('cookies',NULL,'excluded'),
('cooktop','hobs','mapped'),
('cookware','cookware','mapped'),
('corgi plush',NULL,'excluded'),
('corkboard','noticeboards','mapped'),
('corn',NULL,'excluded'),
('costume',NULL,'excluded'),
('cot','cots','mapped'),
('couch','sofas','mapped'),
('couch cushions','cushions','mapped'),
('counter','worktops','mapped'),
('countertop','worktops','mapped'),
('countertops','worktops','mapped'),
('crate','storage boxes','mapped'),
('crib','cots','mapped'),
('cricket bat',NULL,'excluded'),
('crocodile head','ornaments','mapped'),
('croissants',NULL,'excluded'),
('cross-back chairs','dining chairs','mapped'),
('crossback chairs','dining chairs','mapped'),
('cup','mugs','mapped'),
('cups','mugs','mapped'),
('cups and plates','plates','mapped'),
('curtain','curtains','mapped'),
('curtain box','curtain poles','mapped'),
('curtain rod','curtain poles','mapped'),
('curtain valance','valances','mapped'),
('curtains','curtains','mapped'),
('cushion','cushions','mapped'),
('cushioned chairs','chairs','mapped'),
('cushions','cushions','mapped'),
('cutlery','cutlery','mapped'),
('cutout',NULL,'excluded'),
('cutting board','chopping boards','mapped'),
('cutting boards','chopping boards','mapped'),
('cylindrical containers','storage containers','mapped'),
('dark wood',NULL,'excluded'),
('dark wood chairs','chairs','mapped'),
('daybed','daybeds','mapped'),
('decanter','decanters','mapped'),
('deck',NULL,'excluded'),
('deck chair','outdoor chairs','mapped'),
('decor',NULL,'excluded'),
('decoration',NULL,'excluded'),
('decorations',NULL,'excluded'),
('decorative bag',NULL,'excluded'),
('decorative ball','ornaments','mapped'),
('decorative balls','ornaments','mapped'),
('decorative basket','baskets','mapped'),
('decorative bird','ornaments','mapped'),
('decorative birds','ornaments','mapped'),
('decorative board',NULL,'excluded'),
('decorative bottle',NULL,'excluded'),
('decorative bottles',NULL,'excluded'),
('decorative bowl','bowls','mapped'),
('decorative bowls','bowls','mapped'),
('decorative box','storage boxes','mapped'),
('decorative boxes','storage boxes','mapped'),
('decorative branch','flowers','mapped'),
('decorative branches','flowers','mapped'),
('decorative butterfly','ornaments','mapped'),
('decorative cage','ornaments','mapped'),
('decorative container','storage containers','mapped'),
('decorative containers','storage containers','mapped'),
('decorative cup','mugs','mapped'),
('decorative cushions','cushions','mapped'),
('decorative fan','ornaments','mapped'),
('decorative figurine','ornaments','mapped'),
('decorative fish','ornaments','mapped'),
('decorative flags',NULL,'excluded'),
('decorative flower','flowers','mapped'),
('decorative flowers','flowers','mapped'),
('decorative fork','ornaments','mapped'),
('decorative frame','picture frames','mapped'),
('decorative grass','flowers','mapped'),
('decorative heart','ornaments','mapped'),
('decorative item',NULL,'excluded'),
('decorative items',NULL,'excluded'),
('decorative jar','storage jars','mapped'),
('decorative jars','storage jars','mapped'),
('decorative knife','ornaments','mapped'),
('decorative knot','ornaments','mapped'),
('decorative lamp','lamps','mapped'),
('decorative lamp base',NULL,'excluded'),
('decorative lanterns','lanterns','mapped'),
('decorative leaf','ornaments','mapped'),
('decorative leaves','ornaments','mapped'),
('decorative letters','wall decorations','mapped'),
('decorative light fixture','lighting','mapped'),
('decorative mirror','mirrors','mapped'),
('decorative object',NULL,'excluded'),
('decorative objects',NULL,'excluded'),
('decorative orb','ornaments','mapped'),
('decorative ornament','ornaments','mapped'),
('decorative panel',NULL,'excluded'),
('decorative piece',NULL,'excluded'),
('decorative pieces',NULL,'excluded'),
('decorative pillow','cushions','mapped'),
('decorative pillows','cushions','mapped'),
('decorative plant','plants','mapped'),
('decorative plant pot','plant pots','mapped'),
('decorative plants','plants','mapped'),
('decorative plate','plates','mapped'),
('decorative plates','plates','mapped'),
('decorative pots','plant pots','mapped'),
('decorative pumpkin','ornaments','mapped'),
('decorative reed diffuser','reed diffusers','mapped'),
('decorative ring','ornaments','mapped'),
('decorative sculpture','sculptures','mapped'),
('decorative sculptures','sculptures','mapped'),
('decorative shelf','shelving','mapped'),
('decorative shell','ornaments','mapped'),
('decorative shoes','ornaments','mapped'),
('decorative sign',NULL,'excluded'),
('decorative sphere','ornaments','mapped'),
('decorative spoon','ornaments','mapped'),
('decorative star','ornaments','mapped'),
('decorative stars','ornaments','mapped'),
('decorative sticks','ornaments','mapped'),
('decorative throw','throws','mapped'),
('decorative tile','wall tiles','mapped'),
('decorative tray','trays','mapped'),
('decorative tree','plants','mapped'),
('decorative vase','vases','mapped'),
('decorative vases','vases','mapped'),
('decorative wall art','artwork','mapped'),
('decorative wall clock','clocks','mapped'),
('decorative wall decals','wall decals','mapped'),
('decorative wall hanging','wall decorations','mapped'),
('decorative wall hangings','wall decorations','mapped'),
('decorative wall mount','wall decorations','mapped'),
('decorative wall panel','wall panelling','mapped'),
('decorative wall piece','wall decorations','mapped'),
('decorative window fixture',NULL,'excluded'),
('deer head ornament','ornaments','mapped'),
('desk','desks','mapped'),
('desk chair','office chairs','mapped'),
('desk organizer','desk organisers','mapped'),
('dice',NULL,'excluded'),
('diffuser','reed diffusers','mapped'),
('dining bench','dining benches','mapped'),
('dining chair','dining chairs','mapped'),
('dining chairs','dining chairs','mapped'),
('dining table','dining tables','mapped'),
('disco ball',NULL,'excluded'),
('dish rack','dish racks','mapped'),
('dishwasher','dishwashers','mapped'),
('dispenser',NULL,'excluded'),
('display cabinet','display cabinets','mapped'),
('dog',NULL,'excluded'),
('dog bed','pet beds','mapped'),
('dog bowls',NULL,'excluded'),
('dog figurine','ornaments','mapped'),
('dog food container',NULL,'excluded'),
('dog leash',NULL,'excluded'),
('dog statue','ornaments','mapped'),
('doll',NULL,'excluded'),
('doll pram',NULL,'excluded'),
('dollhouse',NULL,'excluded'),
('door',NULL,'excluded'),
('door casing',NULL,'excluded'),
('door frame',NULL,'excluded'),
('door frames',NULL,'excluded'),
('door handle','door handles','mapped'),
('door hinge',NULL,'excluded'),
('door jamb',NULL,'excluded'),
('door latch',NULL,'excluded'),
('door panel',NULL,'excluded'),
('door seal',NULL,'excluded'),
('door sill',NULL,'excluded'),
('door stop','door stops','mapped'),
('door threshold',NULL,'excluded'),
('door trim',NULL,'excluded'),
('door window',NULL,'excluded'),
('doorframe',NULL,'excluded'),
('doormat','doormats','mapped'),
('doors',NULL,'excluded'),
('doorway',NULL,'excluded'),
('doorways',NULL,'excluded'),
('double door',NULL,'excluded'),
('drain',NULL,'excluded'),
('drawer',NULL,'excluded'),
('drawer fronts',NULL,'excluded'),
('drawer unit','chest of drawers','mapped'),
('drawers',NULL,'excluded'),
('drawings','artwork','mapped'),
('dreamcatcher','wall decorations','mapped'),
('dress',NULL,'excluded'),
('dresser','chest of drawers','mapped'),
('dressing stool','stools','mapped'),
('dressing table','dressing tables','mapped'),
('drinks',NULL,'excluded'),
('dry riser outlet box',NULL,'excluded'),
('dryer','tumble dryers','mapped'),
('duffel bag',NULL,'excluded'),
('dumbbell rack',NULL,'excluded'),
('dumbbells',NULL,'excluded'),
('dust mop',NULL,'excluded'),
('duvet','bedding','mapped'),
('easel',NULL,'excluded'),
('electrical outlet',NULL,'excluded'),
('elephant figurine','ornaments','mapped'),
('elevator',NULL,'excluded'),
('elevator control panel',NULL,'excluded'),
('en suite bathroom',NULL,'excluded'),
('entertainment center','tv units','mapped'),
('entertainment unit','tv units','mapped'),
('exercise ball',NULL,'excluded'),
('exercise balls',NULL,'excluded'),
('exercise bike',NULL,'excluded'),
('exercise equipment',NULL,'excluded'),
('exercise mat',NULL,'excluded'),
('exhaust fan',NULL,'excluded'),
('exhaust hood','cooker hoods','mapped'),
('exit sign',NULL,'excluded'),
('extractor','cooker hoods','mapped'),
('extractor fan',NULL,'excluded'),
('extractor hood','cooker hoods','mapped'),
('fabric',NULL,'excluded'),
('fabric canopy','bed canopies','mapped'),
('fabric chair','chairs','mapped'),
('fabric chairs','chairs','mapped'),
('fairy lights','string lights','mapped'),
('fan',NULL,'excluded'),
('faucet','taps','mapped'),
('faucets','taps','mapped'),
('feather decor','ornaments','mapped'),
('feeder',NULL,'excluded'),
('fence',NULL,'excluded'),
('figurine','ornaments','mapped'),
('file holder','desk organisers','mapped'),
('fire extinguisher',NULL,'excluded'),
('fire pit','fire pits','mapped'),
('fire place','fireplaces','mapped'),
('fire truck cabinet','storage units','mapped'),
('fireplace','fireplaces','mapped'),
('fireplace mantel','mantelpieces','mapped'),
('fireplace screen','fireplace screens','mapped'),
('first aid bin',NULL,'excluded'),
('fish decorations','ornaments','mapped'),
('fixed surfaces',NULL,'excluded'),
('fixture',NULL,'excluded'),
('flag',NULL,'excluded'),
('flags',NULL,'excluded'),
('floor',NULL,'excluded'),
('floor cushion','floor cushions','mapped'),
('floor lamp','floor lamps','mapped'),
('floor lamps','floor lamps','mapped'),
('floor mat',NULL,'excluded'),
('floor rug','rugs','mapped'),
('floor tile','floor tiles','mapped'),
('floor tiles','floor tiles','mapped'),
('floor-mounted cabinet','cabinets','mapped'),
('flooring','flooring','mapped'),
('floral wreath','wreaths','mapped'),
('flower','flowers','mapped'),
('flower arrangement','flowers','mapped'),
('flower garland','garlands','mapped'),
('flower vase','vases','mapped'),
('flowers','flowers','mapped'),
('fluffy chair','chairs','mapped'),
('flush plate','toilets','mapped'),
('football',NULL,'excluded'),
('footstool','footstools','mapped'),
('footstools','footstools','mapped'),
('fork','cutlery','mapped'),
('forks','cutlery','mapped'),
('frame',NULL,'excluded'),
('framed art','artwork','mapped'),
('framed artwork','artwork','mapped'),
('framed photos','artwork','mapped'),
('framed picture','artwork','mapped'),
('framed pictures','artwork','mapped'),
('framed poster','artwork','mapped'),
('framed prints','artwork','mapped'),
('framed quote','artwork','mapped'),
('framed sign','wall decorations','mapped'),
('frames',NULL,'excluded'),
('french door','french doors','mapped'),
('french doors','french doors','mapped'),
('fridge','fridges','mapped'),
('fruit',NULL,'excluded'),
('fruit basket',NULL,'excluded'),
('fruit bowl','bowls','mapped'),
('fruit stand',NULL,'excluded'),
('fruits',NULL,'excluded'),
('furnishing',NULL,'excluded'),
('furniture',NULL,'excluded'),
('furry cushion','cushions','mapped'),
('game board',NULL,'excluded'),
('game controller',NULL,'excluded'),
('gaming chair','gaming chairs','mapped'),
('garage door',NULL,'excluded'),
('garland','garlands','mapped'),
('gift',NULL,'excluded'),
('gift box',NULL,'excluded'),
('giraffe',NULL,'excluded'),
('giraffe figurine','ornaments','mapped'),
('giraffe head','ornaments','mapped'),
('giraffe toy',NULL,'excluded'),
('glass','glassware','mapped'),
('glass bottle',NULL,'excluded'),
('glass cabinet','cabinets','mapped'),
('glass coffee table','coffee tables','mapped'),
('glass dining table','dining tables','mapped'),
('glass door',NULL,'excluded'),
('glass doors',NULL,'excluded'),
('glass jar','storage jars','mapped'),
('glass jars','storage jars','mapped'),
('glass partition','room dividers','mapped'),
('glass railing','stair railings','mapped'),
('glass screen','room dividers','mapped'),
('glass shower screen','shower screens','mapped'),
('glass table','tables','mapped'),
('glass vase','vases','mapped'),
('glasses','glassware','mapped'),
('glassware','glassware','mapped'),
('glassware stand','glassware','mapped'),
('globe','ornaments','mapped'),
('gloves',NULL,'excluded'),
('golf bag',NULL,'excluded'),
('golf clubs',NULL,'excluded'),
('golf mat',NULL,'excluded'),
('grand piano',NULL,'excluded'),
('grater','kitchen utensils','mapped'),
('grid','wall organisers','mapped'),
('grid wall organizer','wall organisers','mapped'),
('grid wall panel','wall organisers','mapped'),
('growth chart',NULL,'excluded'),
('guitar',NULL,'excluded'),
('gym bag',NULL,'excluded'),
('hairbrush',NULL,'excluded'),
('hallway',NULL,'excluded'),
('hammock','hammocks','mapped'),
('hand',NULL,'excluded'),
('hand soap',NULL,'excluded'),
('hand soap dispenser','soap dispensers','mapped'),
('hand towel','towels','mapped'),
('handbag',NULL,'excluded'),
('handle',NULL,'excluded'),
('handles',NULL,'excluded'),
('handrail','stair railings','mapped'),
('hanger',NULL,'excluded'),
('hangers',NULL,'excluded'),
('hanging bag',NULL,'excluded'),
('hanging bags',NULL,'excluded'),
('hanging chair','hanging chairs','mapped'),
('hanging clothes',NULL,'excluded'),
('hanging clothes rack','clothes rails','mapped'),
('hanging coat',NULL,'excluded'),
('hanging decoration',NULL,'excluded'),
('hanging garment',NULL,'excluded'),
('hanging hat',NULL,'excluded'),
('hanging hooks','hooks','mapped'),
('hanging lamp','pendant lights','mapped'),
('hanging lamps','pendant lights','mapped'),
('hanging light','pendant lights','mapped'),
('hanging light fixture','pendant lights','mapped'),
('hanging plant','plants','mapped'),
('hanging rack','coat racks','mapped'),
('hanging rail','clothes rails','mapped'),
('hanging range hood','cooker hoods','mapped'),
('hat',NULL,'excluded'),
('hat rack','coat racks','mapped'),
('hat stand','coat racks','mapped'),
('hats',NULL,'excluded'),
('headboard','headboards','mapped'),
('headboard net','bed canopies','mapped'),
('headboard wall','headboards','mapped'),
('headboards','headboards','mapped'),
('headphones',NULL,'excluded'),
('heart decoration','ornaments','mapped'),
('heart ornament','ornaments','mapped'),
('heated towel rail','heated towel rails','mapped'),
('heater',NULL,'excluded'),
('heating radiator','radiators','mapped'),
('heating unit',NULL,'excluded'),
('helmet',NULL,'excluded'),
('high chair','high chairs','mapped'),
('hob','hobs','mapped'),
('hockey stick',NULL,'excluded'),
('hood','cooker hoods','mapped'),
('hook','hooks','mapped'),
('hook rail','hooks','mapped'),
('hooks','hooks','mapped'),
('horse head ornament','ornaments','mapped'),
('horse ornament','ornaments','mapped'),
('horse statue','ornaments','mapped'),
('hourglass','ornaments','mapped'),
('hula hoop',NULL,'excluded'),
('ice bucket','ice buckets','mapped'),
('intercom',NULL,'excluded'),
('island','kitchen islands','mapped'),
('island table','kitchen islands','mapped'),
('jacket',NULL,'excluded'),
('jar','storage jars','mapped'),
('jars','storage jars','mapped'),
('jersey',NULL,'excluded'),
('jug','jugs','mapped'),
('jugs','jugs','mapped'),
('kettle','kettles','mapped'),
('keyboard',NULL,'excluded'),
('kitchen',NULL,'excluded'),
('kitchen appliances',NULL,'excluded'),
('kitchen backsplash','splashbacks','mapped'),
('kitchen cabinet','kitchen cabinets','mapped'),
('kitchen cabinets','kitchen cabinets','mapped'),
('kitchen chairs','dining chairs','mapped'),
('kitchen counter','worktops','mapped'),
('kitchen countertop','worktops','mapped'),
('kitchen countertops','worktops','mapped'),
('kitchen decor',NULL,'excluded'),
('kitchen faucet','taps','mapped'),
('kitchen hood','cooker hoods','mapped'),
('kitchen island','kitchen islands','mapped'),
('kitchen island stools','bar stools','mapped'),
('kitchen scale',NULL,'excluded'),
('kitchen sink','kitchen sinks','mapped'),
('kitchen tools','kitchen utensils','mapped'),
('kitchen unit','kitchen cabinets','mapped'),
('kitchen units','kitchen cabinets','mapped'),
('kitchen utensils','kitchen utensils','mapped'),
('kitchenette',NULL,'excluded'),
('kitchenware',NULL,'excluded'),
('knife','cutlery','mapped'),
('knife block','utensil holders','mapped'),
('knitted ottoman','ottomans','mapped'),
('knives','cutlery','mapped'),
('knobs','cabinet handles','mapped'),
('label',NULL,'excluded'),
('ladder',NULL,'excluded'),
('ladder mirror','mirrors','mapped'),
('ladder rack','towel ladders','mapped'),
('ladder shelf','shelving','mapped'),
('lamp','lamps','mapped'),
('lamp base',NULL,'excluded'),
('lamp bases',NULL,'excluded'),
('lamp shade','lampshades','mapped'),
('lamps','lamps','mapped'),
('lampshade','lampshades','mapped'),
('lampshades','lampshades','mapped'),
('lantern','lanterns','mapped'),
('lanterns','lanterns','mapped'),
('laptop',NULL,'excluded'),
('laptops',NULL,'excluded'),
('laundry bag','laundry baskets','mapped'),
('laundry basket','laundry baskets','mapped'),
('laundry bin','laundry baskets','mapped'),
('lawn',NULL,'excluded'),
('leather',NULL,'excluded'),
('leather chair','chairs','mapped'),
('leather chairs','chairs','mapped'),
('lemon',NULL,'excluded'),
('leopard chair','armchairs','mapped'),
('letter decor','wall decorations','mapped'),
('letterbox',NULL,'excluded'),
('lifebuoy',NULL,'excluded'),
('light','lighting','mapped'),
('light fixture','lighting','mapped'),
('light fixtures','lighting','mapped'),
('light strip','led strip lighting','mapped'),
('light switch',NULL,'excluded'),
('light switches',NULL,'excluded'),
('light wood',NULL,'excluded'),
('light wood bench','benches','mapped'),
('light wood chair','chairs','mapped'),
('light wood chairs','chairs','mapped'),
('light wood dining chairs','dining chairs','mapped'),
('light wood legs',NULL,'excluded'),
('light wood seats','chairs','mapped'),
('light wood stools','stools','mapped'),
('lightbox','neon signs','mapped'),
('lighting','lighting','mapped'),
('lighting fixtures','lighting','mapped'),
('lights','lighting','mapped'),
('lightswitch',NULL,'excluded'),
('locker','storage units','mapped'),
('lockers','storage units','mapped'),
('lotion bottle',NULL,'excluded'),
('luggage',NULL,'excluded'),
('macrame wall hanging','wall decorations','mapped'),
('magazine','magazines','mapped'),
('magazines','magazines','mapped'),
('mannequin',NULL,'excluded'),
('mantelpiece','mantelpieces','mapped'),
('map','artwork','mapped'),
('map wallpaper','wallpaper','mapped'),
('mask',NULL,'excluded'),
('massage table',NULL,'excluded'),
('mat',NULL,'excluded'),
('media cabinet','tv units','mapped'),
('media console','tv units','mapped'),
('media unit','tv units','mapped'),
('mesh',NULL,'excluded'),
('mesh chair','chairs','mapped'),
('metal chair','chairs','mapped'),
('metal chairs','chairs','mapped'),
('metal frame chairs','chairs','mapped'),
('metallic',NULL,'excluded'),
('metallic chair','chairs','mapped'),
('metallic chairs','chairs','mapped'),
('metallic frame',NULL,'excluded'),
('metallic legs',NULL,'excluded'),
('microphone',NULL,'excluded'),
('microscope',NULL,'excluded'),
('microwave','microwaves','mapped'),
('mirror','mirrors','mapped'),
('mirror cabinet','bathroom cabinets','mapped'),
('mirror doors',NULL,'excluded'),
('mirror frame','mirrors','mapped'),
('mirror wall art','mirrors','mapped'),
('mirrors','mirrors','mapped'),
('mobile',NULL,'excluded'),
('model sailboat','ornaments','mapped'),
('model ship','ornaments','mapped'),
('modern chair','chairs','mapped'),
('modern chairs','chairs','mapped'),
('modern dining chairs','dining chairs','mapped'),
('monitor',NULL,'excluded'),
('monkey plush',NULL,'excluded'),
('monkey toys',NULL,'excluded'),
('moon ornament','ornaments','mapped'),
('mop',NULL,'excluded'),
('moss art','sculptures','mapped'),
('mouse',NULL,'excluded'),
('mug','mugs','mapped'),
('mugs','mugs','mapped'),
('mural','wall murals','mapped'),
('mushroom decoration','ornaments','mapped'),
('name wall art','artwork','mapped'),
('napkin','napkins','mapped'),
('napkin rings','napkins','mapped'),
('napkins','napkins','mapped'),
('natural',NULL,'excluded'),
('natural wood chairs','chairs','mapped'),
('natural woven seats','chairs','mapped'),
('neon light','neon signs','mapped'),
('neon sign','neon signs','mapped'),
('net',NULL,'excluded'),
('net canopy','bed canopies','mapped'),
('netting',NULL,'excluded'),
('newspaper',NULL,'excluded'),
('night lamp','table lamps','mapped'),
('nightstand','bedside tables','mapped'),
('nightstands','bedside tables','mapped'),
('notebook',NULL,'excluded'),
('notice board','noticeboards','mapped'),
('noticeboard','noticeboards','mapped'),
('oars',NULL,'excluded'),
('office chair','office chairs','mapped'),
('oranges',NULL,'excluded'),
('ornament','ornaments','mapped'),
('ornaments','ornaments','mapped'),
('ottoman','ottomans','mapped'),
('ottomans','ottomans','mapped'),
('outdoor chairs','outdoor chairs','mapped'),
('outdoor furniture',NULL,'excluded'),
('outdoor table','outdoor tables','mapped'),
('outlet',NULL,'excluded'),
('oven','ovens','mapped'),
('oven hob','hobs','mapped'),
('oven unit','ovens','mapped'),
('paint',NULL,'excluded'),
('paint palette',NULL,'excluded'),
('painting','artwork','mapped'),
('paintings','artwork','mapped'),
('pampas grass','flowers','mapped'),
('pan','cookware','mapped'),
('panda chair','armchairs','mapped'),
('panda plush',NULL,'excluded'),
('partition','room dividers','mapped'),
('pasta containers','storage jars','mapped'),
('patio',NULL,'excluded'),
('patio door','sliding doors','mapped'),
('patio furniture',NULL,'excluded'),
('patterned armchair','armchairs','mapped'),
('patterned chair','chairs','mapped'),
('patterned chairs','chairs','mapped'),
('patterned seats','chairs','mapped'),
('patterned upholstery',NULL,'excluded'),
('pedestal sink','bathroom basins','mapped'),
('peg holder','desk organisers','mapped'),
('pegboard','wall organisers','mapped'),
('pen holder','desk organisers','mapped'),
('pencils',NULL,'excluded'),
('pendant lamp','pendant lights','mapped'),
('pendant lamps','pendant lights','mapped'),
('pendant light','pendant lights','mapped'),
('pendant lights','pendant lights','mapped'),
('pepper mill','salt and pepper mills','mapped'),
('perfume bottle',NULL,'excluded'),
('person',NULL,'excluded'),
('pet bed','pet beds','mapped'),
('pet food bowls',NULL,'excluded'),
('pet food containers',NULL,'excluded'),
('phone',NULL,'excluded'),
('photo frame','picture frames','mapped'),
('photograph frame','picture frames','mapped'),
('photos','artwork','mapped'),
('piano',NULL,'excluded'),
('picnic bench','outdoor benches','mapped'),
('picnic table','outdoor tables','mapped'),
('picture','artwork','mapped'),
('picture frame','picture frames','mapped'),
('picture frames','picture frames','mapped'),
('pictures','artwork','mapped'),
('pillars',NULL,'excluded'),
('pillow','cushions','mapped'),
('pillows','cushions','mapped'),
('pinboard','noticeboards','mapped'),
('pipe',NULL,'excluded'),
('pitcher','jugs','mapped'),
('placemat','placemats','mapped'),
('placemats','placemats','mapped'),
('plaid armchair','armchairs','mapped'),
('plant','plants','mapped'),
('plant basket','baskets','mapped'),
('plant hanger','plant stands','mapped'),
('plant hangers','plant stands','mapped'),
('plant holder','plant stands','mapped'),
('plant pot','plant pots','mapped'),
('plant pots','plant pots','mapped'),
('plant shelf','shelving','mapped'),
('plant stand','plant stands','mapped'),
('planter','plant pots','mapped'),
('planters','plant pots','mapped'),
('plants','plants','mapped'),
('plate','plates','mapped'),
('plates','plates','mapped'),
('plates and bowls','bowls','mapped'),
('play tent','play tents','mapped'),
('plug socket',NULL,'excluded'),
('plush',NULL,'excluded'),
('plush toy',NULL,'excluded'),
('plush toys',NULL,'excluded'),
('popcorn bucket',NULL,'excluded'),
('poster','artwork','mapped'),
('pot','cookware','mapped'),
('pots','cookware','mapped'),
('pots and pans','cookware','mapped'),
('potted plant','plants','mapped'),
('potted plants','plants','mapped'),
('pouf','ottomans','mapped'),
('pouffe','ottomans','mapped'),
('power outlet',NULL,'excluded'),
('power socket',NULL,'excluded'),
('printer',NULL,'excluded'),
('projector',NULL,'excluded'),
('projector screen',NULL,'excluded'),
('promotional panel',NULL,'excluded'),
('propeller',NULL,'excluded'),
('pump bottles',NULL,'excluded'),
('quilt','bedding','mapped'),
('quilted chairs','chairs','mapped'),
('rabbit headboard decoration','ornaments','mapped'),
('rack',NULL,'excluded'),
('radiator','radiators','mapped'),
('radiator cover','radiator covers','mapped'),
('radiators','radiators','mapped'),
('radio',NULL,'excluded'),
('rail',NULL,'excluded'),
('railing','stair railings','mapped'),
('railings','stair railings','mapped'),
('rainbow',NULL,'excluded'),
('rainbow decoration','ornaments','mapped'),
('rainbow ornament','ornaments','mapped'),
('range hood','cooker hoods','mapped'),
('rattan chair','chairs','mapped'),
('receptacle',NULL,'excluded'),
('recessed lighting','recessed lighting','mapped'),
('recessed shelf','shelving','mapped'),
('record player',NULL,'excluded'),
('reed diffuser','reed diffusers','mapped'),
('reeds','flowers','mapped'),
('reeds diffuser','reed diffusers','mapped'),
('refrigerator','fridges','mapped'),
('remote',NULL,'excluded'),
('remote control',NULL,'excluded'),
('ring light',NULL,'excluded'),
('robe',NULL,'excluded'),
('robes',NULL,'excluded'),
('rocking chair','rocking chairs','mapped'),
('rocking elephant',NULL,'excluded'),
('rocking elephant toy',NULL,'excluded'),
('rocking horse',NULL,'excluded'),
('rocking whale toy',NULL,'excluded'),
('roller blind','roller blinds','mapped'),
('rolling pin','kitchen utensils','mapped'),
('roman blind','roman blinds','mapped'),
('room divider','room dividers','mapped'),
('rooster ornament','ornaments','mapped'),
('round mirror','mirrors','mapped'),
('round rug','rugs','mapped'),
('round table','tables','mapped'),
('round wall mirror','mirrors','mapped'),
('rubber ducks',NULL,'excluded'),
('rug','rugs','mapped'),
('rug rack','rug racks','mapped'),
('rugby ball',NULL,'excluded'),
('rugs','rugs','mapped'),
('sailboat','ornaments','mapped'),
('salt and pepper shakers','salt and pepper mills','mapped'),
('salt shaker','salt and pepper mills','mapped'),
('saucer','plates','mapped'),
('scale',NULL,'excluded'),
('scarf',NULL,'excluded'),
('scarves',NULL,'excluded'),
('sconces','wall lights','mapped'),
('scooter',NULL,'excluded'),
('scoreboard',NULL,'excluded'),
('screen',NULL,'excluded'),
('sculpture','sculptures','mapped'),
('sculptures','sculptures','mapped'),
('seahorse ornament','ornaments','mapped'),
('seashell','ornaments','mapped'),
('seashell decor','ornaments','mapped'),
('seating',NULL,'excluded'),
('sewing machine',NULL,'excluded'),
('shaker','salt and pepper mills','mapped'),
('shelf','shelving','mapped'),
('shelf unit','shelving','mapped'),
('shell','ornaments','mapped'),
('shelves','shelving','mapped'),
('shelving','shelving','mapped'),
('shelving unit','shelving','mapped'),
('ship model','ornaments','mapped'),
('shirt',NULL,'excluded'),
('shoe',NULL,'excluded'),
('shoe rack','shoe racks','mapped'),
('shoes',NULL,'excluded'),
('shopping bag',NULL,'excluded'),
('shopping bags',NULL,'excluded'),
('shower','showers','mapped'),
('shower arm','showers','mapped'),
('shower caddy','shower caddies','mapped'),
('shower controls','showers','mapped'),
('shower curtain','shower curtains','mapped'),
('shower curtain rod','shower curtains','mapped'),
('shower door','shower screens','mapped'),
('shower door handle',NULL,'excluded'),
('shower enclosure','shower screens','mapped'),
('shower fixture','showers','mapped'),
('shower glass','shower screens','mapped'),
('shower head','shower heads','mapped'),
('shower hose','showers','mapped'),
('shower rack','shower caddies','mapped'),
('shower rail','showers','mapped'),
('shower screen','shower screens','mapped'),
('shower tray','shower trays','mapped'),
('showerhead','shower heads','mapped'),
('shrub','plants','mapped'),
('shutters','shutters','mapped'),
('side lamp','table lamps','mapped'),
('side table','side tables','mapped'),
('side table lamp','table lamps','mapped'),
('side tables','side tables','mapped'),
('sideboard','sideboards','mapped'),
('sign',NULL,'excluded'),
('signage',NULL,'excluded'),
('signs',NULL,'excluded'),
('sill',NULL,'excluded'),
('sink','sinks','mapped'),
('sink cabinet','vanity units','mapped'),
('sink pedestal','bathroom basins','mapped'),
('sink stand','bathroom basins','mapped'),
('sink unit','vanity units','mapped'),
('sink vanity','vanity units','mapped'),
('sinks','sinks','mapped'),
('skateboard',NULL,'excluded'),
('skateboards',NULL,'excluded'),
('skirting board','skirting boards','mapped'),
('skull',NULL,'excluded'),
('skylight',NULL,'excluded'),
('slide',NULL,'excluded'),
('sliding door','sliding doors','mapped'),
('sliding doors','sliding doors','mapped'),
('sliding glass door','sliding doors','mapped'),
('sliding wardrobe','wardrobes','mapped'),
('slippers',NULL,'excluded'),
('slotted spoon','kitchen utensils','mapped'),
('small mirror','mirrors','mapped'),
('small sofa','sofas','mapped'),
('smoke detector',NULL,'excluded'),
('snail cushion','cushions','mapped'),
('soap',NULL,'excluded'),
('soap bottles',NULL,'excluded'),
('soap dish','soap dishes','mapped'),
('soap dispenser','soap dispensers','mapped'),
('soap dispensers','soap dispensers','mapped'),
('soccer ball',NULL,'excluded'),
('soccer ball pillow','cushions','mapped'),
('soccer balls',NULL,'excluded'),
('socket',NULL,'excluded'),
('sofa','sofas','mapped'),
('sofa chairs','sofas','mapped'),
('soft toy',NULL,'excluded'),
('spatula','kitchen utensils','mapped'),
('speaker',NULL,'excluded'),
('spice bottles','storage jars','mapped'),
('spice jars','storage jars','mapped'),
('spices',NULL,'excluded'),
('spindle chair','dining chairs','mapped'),
('splashback','splashbacks','mapped'),
('sponge',NULL,'excluded'),
('spoon','cutlery','mapped'),
('spoons','cutlery','mapped'),
('sports memorabilia',NULL,'excluded'),
('spotlight','spotlights','mapped'),
('spotlights','spotlights','mapped'),
('spray bottle',NULL,'excluded'),
('spray bottles',NULL,'excluded'),
('stair rail','stair railings','mapped'),
('staircase','staircases','mapped'),
('staircase balustrade','stair railings','mapped'),
('stairs','staircases','mapped'),
('stairs railing','stair railings','mapped'),
('stand',NULL,'excluded'),
('star',NULL,'excluded'),
('star decoration','ornaments','mapped'),
('star decorations','ornaments','mapped'),
('star ornament','ornaments','mapped'),
('star wall decor','wall decorations','mapped'),
('star wall hangings','wall decorations','mapped'),
('starfish ornament','ornaments','mapped'),
('stars',NULL,'excluded'),
('statue','ornaments','mapped'),
('statues','ornaments','mapped'),
('stool','stools','mapped'),
('stools','stools','mapped'),
('storage',NULL,'excluded'),
('storage bag',NULL,'excluded'),
('storage basket','baskets','mapped'),
('storage baskets','baskets','mapped'),
('storage bench','storage benches','mapped'),
('storage bin','bins','mapped'),
('storage box','storage boxes','mapped'),
('storage boxes','storage boxes','mapped'),
('storage cabinet','cabinets','mapped'),
('storage canisters','storage jars','mapped'),
('storage cart','bar carts','mapped'),
('storage chest','storage chests','mapped'),
('storage container','storage containers','mapped'),
('storage jar','storage jars','mapped'),
('storage jars','storage jars','mapped'),
('storage rack','storage racks','mapped'),
('storage shelf','shelving','mapped'),
('storage unit','storage units','mapped'),
('stove','hobs','mapped'),
('stovetop','hobs','mapped'),
('string light fixture','string lights','mapped'),
('string lights','string lights','mapped'),
('striped armchair','armchairs','mapped'),
('striped chair','chairs','mapped'),
('striped chairs','chairs','mapped'),
('striped cushions','cushions','mapped'),
('striped towel','towels','mapped'),
('stroller',NULL,'excluded'),
('studded chair','chairs','mapped'),
('studded chairs','chairs','mapped'),
('stuffed animal',NULL,'excluded'),
('stuffed animals',NULL,'excluded'),
('stuffed bear',NULL,'excluded'),
('stuffed giraffe',NULL,'excluded'),
('stuffed octopus',NULL,'excluded'),
('stuffed rabbit',NULL,'excluded'),
('stuffed rabbits',NULL,'excluded'),
('stuffed toy',NULL,'excluded'),
('stuffed toys',NULL,'excluded'),
('suitcase',NULL,'excluded'),
('sun',NULL,'excluded'),
('sun decoration','ornaments','mapped'),
('sunflowers','flowers','mapped'),
('surfboard',NULL,'excluded'),
('swing chair','hanging chairs','mapped'),
('switch',NULL,'excluded'),
('swivel chair','chairs','mapped'),
('t-shirt',NULL,'excluded'),
('table','tables','mapped'),
('table lamp','table lamps','mapped'),
('table lamps','table lamps','mapped'),
('table runner','table runners','mapped'),
('tablecloth','tablecloths','mapped'),
('tables','tables','mapped'),
('tablet',NULL,'excluded'),
('tableware','tableware','mapped'),
('tajine','cookware','mapped'),
('tan',NULL,'excluded'),
('tap','taps','mapped'),
('tapestry','wall decorations','mapped'),
('taps','taps','mapped'),
('teapot','teapots','mapped'),
('teapot and mug','teapots','mapped'),
('teapot set','teapots','mapped'),
('teddy bear',NULL,'excluded'),
('teddy bears',NULL,'excluded'),
('teepee','play tents','mapped'),
('telephone',NULL,'excluded'),
('telescope',NULL,'excluded'),
('television',NULL,'excluded'),
('television stand','tv units','mapped'),
('tennis racket',NULL,'excluded'),
('tent',NULL,'excluded'),
('tents',NULL,'excluded'),
('tepee','play tents','mapped'),
('text box',NULL,'excluded'),
('textured chairs','chairs','mapped'),
('thermostat',NULL,'excluded'),
('throw','throws','mapped'),
('throw blanket','throws','mapped'),
('tiger',NULL,'excluded'),
('tiki statue','ornaments','mapped'),
('tiled floor','floor tiles','mapped'),
('tiled wall','wall tiles','mapped'),
('tiles','tiles','mapped'),
('tissue box','tissue boxes','mapped'),
('tissue holder','tissue boxes','mapped'),
('toaster','toasters','mapped'),
('toilet','toilets','mapped'),
('toilet brush','toilet brushes','mapped'),
('toilet brush holder','toilet brushes','mapped'),
('toilet cistern','toilets','mapped'),
('toilet flush plate','toilets','mapped'),
('toilet paper',NULL,'excluded'),
('toilet paper holder','toilet roll holders','mapped'),
('toilet roll holder','toilet roll holders','mapped'),
('toiletries',NULL,'excluded'),
('tomatoes',NULL,'excluded'),
('tool',NULL,'excluded'),
('tool wall','wall organisers','mapped'),
('toothbrush holder','toothbrush holders','mapped'),
('tote bag',NULL,'excluded'),
('towel','towels','mapped'),
('towel bag',NULL,'excluded'),
('towel bar','towel rails','mapped'),
('towel basket','baskets','mapped'),
('towel case',NULL,'excluded'),
('towel dispenser','towel rails','mapped'),
('towel holder','towel rails','mapped'),
('towel ladder','towel ladders','mapped'),
('towel on floor','towels','mapped'),
('towel on toilet','towels','mapped'),
('towel on warmer','towels','mapped'),
('towel rack','towel rails','mapped'),
('towel radiator','heated towel rails','mapped'),
('towel rail','towel rails','mapped'),
('towel ring','towel rails','mapped'),
('towel roll','towels','mapped'),
('towel shelf','towel rails','mapped'),
('towel stack','towels','mapped'),
('towel stand','towel rails','mapped'),
('towel tray','trays','mapped'),
('towel warmer','heated towel rails','mapped'),
('towels','towels','mapped'),
('toy',NULL,'excluded'),
('toy basket','baskets','mapped'),
('toy bed',NULL,'excluded'),
('toy box','storage boxes','mapped'),
('toy bus',NULL,'excluded'),
('toy car',NULL,'excluded'),
('toy cars',NULL,'excluded'),
('toy cart',NULL,'excluded'),
('toy castle',NULL,'excluded'),
('toy elephant',NULL,'excluded'),
('toy excavator',NULL,'excluded'),
('toy house',NULL,'excluded'),
('toy kitchen',NULL,'excluded'),
('toy shelf','toy storage','mapped'),
('toy stand','toy storage','mapped'),
('toy storage','toy storage','mapped'),
('toy table','play tables','mapped'),
('toy tea set',NULL,'excluded'),
('toy tractor',NULL,'excluded'),
('toy train',NULL,'excluded'),
('toy train table','play tables','mapped'),
('toy truck',NULL,'excluded'),
('toys',NULL,'excluded'),
('toys box','storage boxes','mapped'),
('track lighting','track lighting','mapped'),
('trash bin','bins','mapped'),
('trash can','bins','mapped'),
('tray','trays','mapped'),
('tray table','side tables','mapped'),
('trays','trays','mapped'),
('treadmill',NULL,'excluded'),
('treats container',NULL,'excluded'),
('tree decoration','ornaments','mapped'),
('trim',NULL,'excluded'),
('trolley','bar carts','mapped'),
('trophy',NULL,'excluded'),
('trunk','storage chests','mapped'),
('trunks','storage chests','mapped'),
('tub','baths','mapped'),
('tub tray','bath trays','mapped'),
('tufted armchair','armchairs','mapped'),
('tufted chair','chairs','mapped'),
('tufted chairs','chairs','mapped'),
('tumble dryer','tumble dryers','mapped'),
('turntables',NULL,'excluded'),
('tv',NULL,'excluded'),
('tv cabinet','tv units','mapped'),
('tv shelf','tv units','mapped'),
('tv stand','tv units','mapped'),
('tv unit','tv units','mapped'),
('tv wall unit','tv units','mapped'),
('typewriter',NULL,'excluded'),
('umbrella',NULL,'excluded'),
('umbrella stand','umbrella stands','mapped'),
('upholstered bench','benches','mapped'),
('upholstered chair','chairs','mapped'),
('upholstered chairs','chairs','mapped'),
('urn','vases','mapped'),
('utensil','kitchen utensils','mapped'),
('utensil holder','utensil holders','mapped'),
('utensils','kitchen utensils','mapped'),
('valance','valances','mapped'),
('valve',NULL,'excluded'),
('vanity','vanity units','mapped'),
('vanity cabinet','vanity units','mapped'),
('vanity unit','vanity units','mapped'),
('vase','vases','mapped'),
('vases','vases','mapped'),
('vegetable',NULL,'excluded'),
('velvet armchair','armchairs','mapped'),
('velvet chair','chairs','mapped'),
('velvet chairs','chairs','mapped'),
('vent',NULL,'excluded'),
('vest',NULL,'excluded'),
('vine','plants','mapped'),
('wall',NULL,'excluded'),
('wall art','artwork','mapped'),
('wall cabinet','cabinets','mapped'),
('wall clock','clocks','mapped'),
('wall decal','wall decals','mapped'),
('wall decals','wall decals','mapped'),
('wall decor','wall decorations','mapped'),
('wall decoration','wall decorations','mapped'),
('wall decorations','wall decorations','mapped'),
('wall grid','wall organisers','mapped'),
('wall hanging','wall decorations','mapped'),
('wall heater',NULL,'excluded'),
('wall hooks','hooks','mapped'),
('wall lamp','wall lights','mapped'),
('wall lamps','wall lights','mapped'),
('wall light','wall lights','mapped'),
('wall mirror','mirrors','mapped'),
('wall mirrors','mirrors','mapped'),
('wall mural','wall murals','mapped'),
('wall niche','wall niches','mapped'),
('wall ornament','wall decorations','mapped'),
('wall outlet',NULL,'excluded'),
('wall outlets',NULL,'excluded'),
('wall panel','wall panelling','mapped'),
('wall paneling','wall panelling','mapped'),
('wall planter','wall planters','mapped'),
('wall plates','wall decorations','mapped'),
('wall rack','storage racks','mapped'),
('wall sconce','wall lights','mapped'),
('wall sconces','wall lights','mapped'),
('wall shelf','shelving','mapped'),
('wall shelves','shelving','mapped'),
('wall sign','wall decorations','mapped'),
('wall socket',NULL,'excluded'),
('wall sockets',NULL,'excluded'),
('wall switch',NULL,'excluded'),
('wall tile','wall tiles','mapped'),
('wall tiles','wall tiles','mapped'),
('wall unit','storage units','mapped'),
('wall-mounted basket','baskets','mapped'),
('wall-mounted baskets','baskets','mapped'),
('wall-mounted board',NULL,'excluded'),
('wall-mounted boiler',NULL,'excluded'),
('wall-mounted box','storage boxes','mapped'),
('wall-mounted cabinet','cabinets','mapped'),
('wall-mounted circular device',NULL,'excluded'),
('wall-mounted clock','clocks','mapped'),
('wall-mounted controls',NULL,'excluded'),
('wall-mounted device',NULL,'excluded'),
('wall-mounted heater',NULL,'excluded'),
('wall-mounted holder',NULL,'excluded'),
('wall-mounted hooks','hooks','mapped'),
('wall-mounted lamp','wall lights','mapped'),
('wall-mounted lantern','lanterns','mapped'),
('wall-mounted light','wall lights','mapped'),
('wall-mounted phone',NULL,'excluded'),
('wall-mounted plant holder','plant stands','mapped'),
('wall-mounted plant holders','plant stands','mapped'),
('wall-mounted planter grid','wall planters','mapped'),
('wall-mounted planters','wall planters','mapped'),
('wall-mounted rack','storage racks','mapped'),
('wall-mounted radiator','radiators','mapped'),
('wall-mounted shelf','shelving','mapped'),
('wall-mounted soap dispenser','soap dispensers','mapped'),
('wall-mounted switch',NULL,'excluded'),
('wall-mounted toilet','toilets','mapped'),
('wall-mounted toilet cistern','toilets','mapped'),
('wall-mounted toilet flush','toilets','mapped'),
('wall-mounted toilet flush plate','toilets','mapped'),
('wall-mounted toilet paper holder','toilet roll holders','mapped'),
('wall-mounted tv',NULL,'excluded'),
('wall-mounted unit','storage units','mapped'),
('wallpaper','wallpaper','mapped'),
('wallpaper mural','wall murals','mapped'),
('walls',NULL,'excluded'),
('wardrobe','wardrobes','mapped'),
('wardrobes','wardrobes','mapped'),
('washbasin','bathroom basins','mapped'),
('washing machine','washing machines','mapped'),
('washing machines','washing machines','mapped'),
('waste basket','bins','mapped'),
('waste bin','bins','mapped'),
('water bottle',NULL,'excluded'),
('water heater',NULL,'excluded'),
('water jug','jugs','mapped'),
('water pitcher','jugs','mapped'),
('watering can',NULL,'excluded'),
('whale ornament','ornaments','mapped'),
('whisk','kitchen utensils','mapped'),
('whiteboard','noticeboards','mapped'),
('wicker bar stools','bar stools','mapped'),
('wicker basket','baskets','mapped'),
('wicker baskets','baskets','mapped'),
('wicker chair','chairs','mapped'),
('wicker chairs','chairs','mapped'),
('wicker chest','storage chests','mapped'),
('wicker dining chairs','dining chairs','mapped'),
('wicker storage',NULL,'excluded'),
('wicker storage container','storage containers','mapped'),
('wicker tray','trays','mapped'),
('window',NULL,'excluded'),
('window blind','blinds','mapped'),
('window blinds','blinds','mapped'),
('window decor','wall decorations','mapped'),
('window decoration','wall decorations','mapped'),
('window frame',NULL,'excluded'),
('window frames',NULL,'excluded'),
('window handle',NULL,'excluded'),
('window ornament','wall decorations','mapped'),
('window seat','window seats','mapped'),
('window sign',NULL,'excluded'),
('window sill',NULL,'excluded'),
('window sill decor','wall decorations','mapped'),
('window sill decoration','wall decorations','mapped'),
('window sill ornament','wall decorations','mapped'),
('window sill ornaments','wall decorations','mapped'),
('window sills',NULL,'excluded'),
('window treatment','blinds','mapped'),
('window treatments','blinds','mapped'),
('window valance','valances','mapped'),
('windows',NULL,'excluded'),
('windowsill',NULL,'excluded'),
('wine bottle',NULL,'excluded'),
('wine bottles',NULL,'excluded'),
('wine cabinet','wine cabinets','mapped'),
('wine cooler','wine fridges','mapped'),
('wine fridge','wine fridges','mapped'),
('wine glass','wine glasses','mapped'),
('wine glasses','wine glasses','mapped'),
('wine rack','wine racks','mapped'),
('wire basket','baskets','mapped'),
('wire chair','chairs','mapped'),
('wood',NULL,'excluded'),
('wood and metal bar stools','bar stools','mapped'),
('wood chair','chairs','mapped'),
('wood chairs','chairs','mapped'),
('wood panel','wall panelling','mapped'),
('wood stools','stools','mapped'),
('wooden accent wall','wall panelling','mapped'),
('wooden armchair','armchairs','mapped'),
('wooden armchairs','armchairs','mapped'),
('wooden bar stools','bar stools','mapped'),
('wooden barstools','bar stools','mapped'),
('wooden basin','bathroom basins','mapped'),
('wooden bath mat','bath mats','mapped'),
('wooden bath tray','bath trays','mapped'),
('wooden bench','benches','mapped'),
('wooden blocks',NULL,'excluded'),
('wooden boat bed','beds','mapped'),
('wooden bowl','bowls','mapped'),
('wooden box','storage boxes','mapped'),
('wooden brush',NULL,'excluded'),
('wooden cabinet','cabinets','mapped'),
('wooden castle',NULL,'excluded'),
('wooden chair','chairs','mapped'),
('wooden chairs','chairs','mapped'),
('wooden crate','storage boxes','mapped'),
('wooden cutting board','chopping boards','mapped'),
('wooden cutting boards','chopping boards','mapped'),
('wooden dining chairs','dining chairs','mapped'),
('wooden door',NULL,'excluded'),
('wooden door panel',NULL,'excluded'),
('wooden floor','flooring','mapped'),
('wooden ladder shelf','shelving','mapped'),
('wooden legs',NULL,'excluded'),
('wooden panel','wall panelling','mapped'),
('wooden partition','room dividers','mapped'),
('wooden rabbit',NULL,'excluded'),
('wooden shelf','shelving','mapped'),
('wooden side table','side tables','mapped'),
('wooden spoons','cutlery','mapped'),
('wooden stool','stools','mapped'),
('wooden stools','stools','mapped'),
('wooden structure',NULL,'excluded'),
('wooden table','tables','mapped'),
('wooden tray','trays','mapped'),
('wooden utensil holder','utensil holders','mapped'),
('wooden utensils','kitchen utensils','mapped'),
('workbench','desks','mapped'),
('worktop','worktops','mapped'),
('world map','artwork','mapped'),
('world map rug','rugs','mapped'),
('woven',NULL,'excluded'),
('woven bar stools','bar stools','mapped'),
('woven basket','baskets','mapped'),
('woven baskets','baskets','mapped'),
('woven chair','chairs','mapped'),
('woven chairs','chairs','mapped'),
('woven seat','chairs','mapped'),
('wreath','wreaths','mapped'),
('yoga mat',NULL,'excluded'),
('zebra head ornament','ornaments','mapped')
on conflict(source_name) do update set category_name=excluded.category_name,decision=excluded.decision;
-- Approved category labels are also aliases, so future classifiers may emit
-- the controlled vocabulary directly without sending known types to review.
insert into showhome_web.furnishing_category_mappings(source_name,category_name,decision)
 select distinct category_name,category_name,'mapped'
 from showhome_web.furnishing_category_mappings where category_name is not null
 on conflict(source_name) do nothing;
-- Invalidate once per taxonomy batch. Counts deduplicate mapped image links.
delete from showhome_web.query_cache;
delete from showhome_web.gallery_publication_summaries;
analyze showhome_web.furnishing_category_mappings;
